// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AccountPublic
 */
export type AccountPublic = {
    /**
     * Advertiser Id
     */
    advertiser_id: string;
    /**
     * Bc Id
     */
    bc_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Remote Status
     */
    remote_status: string;
    /**
     * Ownership Conflict
     */
    ownership_conflict: boolean;
    /**
     * Can Build
     */
    can_build: boolean;
    /**
     * Can Upload
     */
    can_upload: boolean;
    /**
     * Permission State
     */
    permission_state: string;
    /**
     * Availability
     */
    availability: 'AVAILABLE' | 'PERMISSION_UNKNOWN' | 'NO_ACCESS' | 'OWNERSHIP_CONFLICT' | 'METADATA_INCOMPLETE';
    /**
     * Checked At
     */
    checked_at: string | null;
};

/**
 * AppConfiguration
 */
export type AppConfiguration = {
    /**
     * Code
     */
    code?: string | null;
    /**
     * Configured
     */
    configured: boolean;
    /**
     * Status
     */
    status: 'READY' | 'NOT_CONFIGURED' | 'INCOMPLETE';
    /**
     * Missing Fields
     */
    missing_fields: Array<string>;
};

/**
 * AppendVersionRequest
 */
export type AppendVersionRequest = {
    config: StrategyConfig_Input;
    /**
     * Expected Version
     */
    expected_version: number;
    /**
     * Request Id
     */
    request_id: string;
};

/**
 * AuthorizationRequest
 */
export type AuthorizationRequest = {
    /**
     * Connection Id
     */
    connection_id?: string | null;
};

/**
 * AuthorizationURL
 */
export type AuthorizationURL = {
    /**
     * Url
     */
    url: string;
};

/**
 * BCPublic
 */
export type BCPublic = {
    /**
     * Bc Id
     */
    bc_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Ownership Conflict
     */
    ownership_conflict: boolean;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CandidateSelection
 */
export type CandidateSelection = {
    /**
     * External Drama Id
     */
    external_drama_id: string;
};

/**
 * ConnectionPublic
 *
 * Explicit allowlist: never serialize ORM credential fields to HTTP.
 */
export type ConnectionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Status
     */
    status: 'PENDING_AUTH' | 'DISCOVERING' | 'ACTIVE' | 'REAUTH_REQUIRED' | 'ERROR' | 'DISABLED';
    /**
     * Last Discovery
     */
    last_discovery?: string | null;
    /**
     * Last Authorized At
     */
    last_authorized_at?: string | null;
    /**
     * Discovery Status
     */
    discovery_status?: 'QUEUED' | 'RUNNING' | 'ADMISSION_WAIT' | 'ERROR' | 'COMPLETE' | 'CANCELLED' | null;
    /**
     * Error Code
     */
    error_code?: string | null;
};

/**
 * ConnectionUpdate
 */
export type ConnectionUpdate = {
    /**
     * Status
     */
    status: 'DISABLED';
};

/**
 * CopyPoolPublic
 */
export type CopyPoolPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Entries
     */
    entries: Array<CopyPublic>;
};

/**
 * CopyPublic
 */
export type CopyPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Text
     */
    text: string;
    /**
     * Position
     */
    position: number;
};

/**
 * CreateStrategyRequest
 */
export type CreateStrategyRequest = {
    /**
     * Name
     */
    name: string;
    config: StrategyConfig_Input;
    /**
     * Request Id
     */
    request_id: string;
};

/**
 * DramaCandidate
 */
export type DramaCandidate = {
    /**
     * External Drama Id
     */
    external_drama_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Language
     */
    language?: string | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InputLine
 */
export type InputLine = {
    /**
     * Line No
     */
    line_no: number;
    /**
     * Raw
     */
    raw: string;
};

/**
 * LinkPreparationRequest
 */
export type LinkPreparationRequest = {
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * Lines
     */
    lines: Array<string>;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
};

/**
 * MemberPublic
 */
export type MemberPublic = {
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role: 'tenant_admin' | 'operator' | 'viewer';
    /**
     * Active
     */
    active: boolean;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * User Active
     */
    user_active: boolean;
};

/**
 * MemberSet
 */
export type MemberSet = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role: 'tenant_admin' | 'operator' | 'viewer';
    /**
     * Active
     */
    active: boolean;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * Page[AccountPublic]
 */
export type Page_AccountPublic_ = {
    /**
     * Items
     */
    items: Array<AccountPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[BCPublic]
 */
export type Page_BCPublic_ = {
    /**
     * Items
     */
    items: Array<BCPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[ConnectionPublic]
 */
export type Page_ConnectionPublic_ = {
    /**
     * Items
     */
    items: Array<ConnectionPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[MemberPublic]
 */
export type Page_MemberPublic_ = {
    /**
     * Items
     */
    items: Array<MemberPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[ProviderApplicationPublic]
 */
export type Page_ProviderApplicationPublic_ = {
    /**
     * Items
     */
    items: Array<ProviderApplicationPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[ProviderConnectionPublic]
 */
export type Page_ProviderConnectionPublic_ = {
    /**
     * Items
     */
    items: Array<ProviderConnectionPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[ResolvedLink]
 */
export type Page_ResolvedLink_ = {
    /**
     * Items
     */
    items: Array<ResolvedLink>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[StrategyPublic]
 */
export type Page_StrategyPublic_ = {
    /**
     * Items
     */
    items: Array<StrategyPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[TenantSummary]
 */
export type Page_TenantSummary_ = {
    /**
     * Items
     */
    items: Array<TenantSummary>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[UserCandidate]
 */
export type Page_UserCandidate_ = {
    /**
     * Items
     */
    items: Array<UserCandidate>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[VersionPublic]
 */
export type Page_VersionPublic_ = {
    /**
     * Items
     */
    items: Array<VersionPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * PreparationAccepted
 */
export type PreparationAccepted = {
    /**
     * Task Id
     */
    task_id: string;
};

/**
 * ProviderApplicationPublic
 */
export type ProviderApplicationPublic = {
    /**
     * External Id
     */
    external_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Tiktok Minis Id
     */
    tiktok_minis_id?: string | null;
    /**
     * Available
     */
    available: boolean;
};

/**
 * ProviderConnectionCreate
 */
export type ProviderConnectionCreate = {
    /**
     * Kind
     */
    kind: 'wangyan' | 'jiashu';
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Credentials
     */
    credentials: {
        [key: string]: string;
    };
};

/**
 * ProviderConnectionPublic
 */
export type ProviderConnectionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Verified At
     */
    verified_at?: string | null;
    /**
     * Error Code
     */
    error_code?: string | null;
};

/**
 * ProviderConnectionUpdate
 */
export type ProviderConnectionUpdate = {
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Credentials
     */
    credentials?: {
        [key: string]: string;
    } | null;
    /**
     * Status
     */
    status?: 'disabled' | null;
};

/**
 * ResolveRequest
 */
export type ResolveRequest = {
    /**
     * Bc Id
     */
    bc_id: string;
    /**
     * Lines
     */
    lines: Array<InputLine>;
};

/**
 * ResolvedLine
 */
export type ResolvedLine = {
    /**
     * Line No
     */
    line_no: number;
    /**
     * Raw
     */
    raw: string;
    /**
     * Status
     */
    status: 'MATCHED' | 'DUPLICATE' | 'AMBIGUOUS' | 'NOT_FOUND' | 'EMPTY' | 'BLOCKED';
    /**
     * Advertiser Id
     */
    advertiser_id?: string | null;
    /**
     * Candidates
     */
    candidates?: Array<string>;
    /**
     * Duplicate Of
     */
    duplicate_of?: number | null;
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * ResolvedLink
 */
export type ResolvedLink = {
    /**
     * Input Id
     */
    input_id: string;
    /**
     * Line No
     */
    line_no: number;
    /**
     * Raw Input
     */
    raw_input: string;
    /**
     * Provider Kind
     */
    provider_kind: string;
    /**
     * Connection Id
     */
    connection_id: string;
    /**
     * Application Id
     */
    application_id: string;
    /**
     * Drama Id
     */
    drama_id?: string | null;
    /**
     * External Drama Id
     */
    external_drama_id?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Link Id
     */
    link_id?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Protected Base
     */
    protected_base?: string | null;
    /**
     * Tiktok Minis Id
     */
    tiktok_minis_id?: string | null;
    /**
     * Status
     */
    status: 'pending' | 'needs_resolution' | 'blocked_auth' | 'config_conflict' | 'retryable_error' | 'result_unknown' | 'failed' | 'ready';
    /**
     * Candidates
     */
    candidates?: Array<DramaCandidate>;
    /**
     * Error Code
     */
    error_code?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * StrategyConfig
 */
export type StrategyConfig_Input = {
    /**
     * Budget
     */
    budget: number | string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Target Roas
     */
    target_roas: number | string;
    /**
     * Group Size
     */
    group_size: number;
    /**
     * Creative Count
     */
    creative_count: number;
    /**
     * Copy Pool Version
     */
    copy_pool_version: string;
    /**
     * Cta Option Ids
     */
    cta_option_ids?: Array<string>;
    /**
     * Campaign Suffix
     */
    campaign_suffix?: string;
};

/**
 * StrategyConfig
 */
export type StrategyConfig_Output = {
    /**
     * Budget
     */
    budget: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Target Roas
     */
    target_roas: string;
    /**
     * Group Size
     */
    group_size: number;
    /**
     * Creative Count
     */
    creative_count: number;
    /**
     * Copy Pool Version
     */
    copy_pool_version: string;
    /**
     * Cta Option Ids
     */
    cta_option_ids?: Array<string>;
    /**
     * Campaign Suffix
     */
    campaign_suffix?: string;
};

/**
 * StrategyPublic
 */
export type StrategyPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Active
     */
    active: boolean;
    /**
     * Latest Version
     */
    latest_version: number;
    /**
     * Version Id
     */
    version_id: string;
    config: StrategyConfig_Output;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * StrategyStateRequest
 */
export type StrategyStateRequest = {
    /**
     * Active
     */
    active: boolean;
};

/**
 * Tenant
 */
export type Tenant = {
    /**
     * Id
     */
    id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Active
     */
    active?: boolean;
};

/**
 * TenantCreate
 */
export type TenantCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Administrator Id
     */
    administrator_id: string;
};

/**
 * TenantSummary
 */
export type TenantSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Active
     */
    active: boolean;
    /**
     * Role
     */
    role: 'platform_admin' | 'tenant_admin' | 'operator' | 'viewer';
};

/**
 * TenantUpdate
 */
export type TenantUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Active
     */
    active?: boolean | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCandidate
 */
export type UserCandidate = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ValidationIssue
 */
export type ValidationIssue = {
    /**
     * Field
     */
    field: string;
    /**
     * Code
     */
    code: string;
};

/**
 * ValidationResult
 */
export type ValidationResult = {
    /**
     * Valid
     */
    valid: boolean;
    /**
     * Errors
     */
    errors: Array<ValidationIssue>;
    /**
     * Scene Check Pending
     */
    scene_check_pending?: boolean;
};

/**
 * VersionPublic
 */
export type VersionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Strategy Id
     */
    strategy_id: string;
    /**
     * Number
     */
    number: number;
    config: StrategyConfig_Output;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Request Id
     */
    request_id: string;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type integrationsTiktokCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/tiktok/callback';
};

export type integrationsTiktokCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type tenantsGetPlatformUserCandidatesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * After Id
         */
        after_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/platform/user-candidates';
};

export type tenantsGetPlatformUserCandidatesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsGetPlatformUserCandidatesError = tenantsGetPlatformUserCandidatesErrors[keyof tenantsGetPlatformUserCandidatesErrors];

export type tenantsGetPlatformUserCandidatesResponses = {
    /**
     * Successful Response
     */
    200: Page_UserCandidate_;
};

export type tenantsGetPlatformUserCandidatesResponse = tenantsGetPlatformUserCandidatesResponses[keyof tenantsGetPlatformUserCandidatesResponses];

export type tenantsGetMemberCandidatesData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * After Id
         */
        after_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/tenants/{tenant_id}/member-candidates';
};

export type tenantsGetMemberCandidatesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsGetMemberCandidatesError = tenantsGetMemberCandidatesErrors[keyof tenantsGetMemberCandidatesErrors];

export type tenantsGetMemberCandidatesResponses = {
    /**
     * Successful Response
     */
    200: Page_UserCandidate_;
};

export type tenantsGetMemberCandidatesResponse = tenantsGetMemberCandidatesResponses[keyof tenantsGetMemberCandidatesResponses];

export type tenantsGetMyTenantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * After Id
         */
        after_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string;
        /**
         * Active
         */
        active?: boolean | null;
    };
    url: '/api/me/tenants';
};

export type tenantsGetMyTenantsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsGetMyTenantsError = tenantsGetMyTenantsErrors[keyof tenantsGetMyTenantsErrors];

export type tenantsGetMyTenantsResponses = {
    /**
     * Successful Response
     */
    200: Page_TenantSummary_;
};

export type tenantsGetMyTenantsResponse = tenantsGetMyTenantsResponses[keyof tenantsGetMyTenantsResponses];

export type tenantsGetPlatformTenantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * After Id
         */
        after_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string;
        /**
         * Active
         */
        active?: boolean | null;
    };
    url: '/api/platform/tenants';
};

export type tenantsGetPlatformTenantsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsGetPlatformTenantsError = tenantsGetPlatformTenantsErrors[keyof tenantsGetPlatformTenantsErrors];

export type tenantsGetPlatformTenantsResponses = {
    /**
     * Successful Response
     */
    200: Page_TenantSummary_;
};

export type tenantsGetPlatformTenantsResponse = tenantsGetPlatformTenantsResponses[keyof tenantsGetPlatformTenantsResponses];

export type tenantsPostTenantData = {
    body: TenantCreate;
    path?: never;
    query?: never;
    url: '/api/platform/tenants';
};

export type tenantsPostTenantErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsPostTenantError = tenantsPostTenantErrors[keyof tenantsPostTenantErrors];

export type tenantsPostTenantResponses = {
    /**
     * Successful Response
     */
    201: Tenant;
};

export type tenantsPostTenantResponse = tenantsPostTenantResponses[keyof tenantsPostTenantResponses];

export type tenantsPatchTenantData = {
    body: TenantUpdate;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/platform/tenants/{tenant_id}';
};

export type tenantsPatchTenantErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsPatchTenantError = tenantsPatchTenantErrors[keyof tenantsPatchTenantErrors];

export type tenantsPatchTenantResponses = {
    /**
     * Successful Response
     */
    200: Tenant;
};

export type tenantsPatchTenantResponse = tenantsPatchTenantResponses[keyof tenantsPatchTenantResponses];

export type tenantsGetMembersData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: {
        /**
         * After Id
         */
        after_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string;
        /**
         * Role
         */
        role?: 'tenant_admin' | 'operator' | 'viewer' | null;
        /**
         * Active
         */
        active?: boolean | null;
    };
    url: '/api/tenants/{tenant_id}/members';
};

export type tenantsGetMembersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsGetMembersError = tenantsGetMembersErrors[keyof tenantsGetMembersErrors];

export type tenantsGetMembersResponses = {
    /**
     * Successful Response
     */
    200: Page_MemberPublic_;
};

export type tenantsGetMembersResponse = tenantsGetMembersResponses[keyof tenantsGetMembersResponses];

export type tenantsPutMemberData = {
    body: MemberSet;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/members';
};

export type tenantsPutMemberErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsPutMemberError = tenantsPutMemberErrors[keyof tenantsPutMemberErrors];

export type tenantsPutMemberResponses = {
    /**
     * Successful Response
     */
    200: MemberPublic;
};

export type tenantsPutMemberResponse = tenantsPutMemberResponses[keyof tenantsPutMemberResponses];

export type accountsGetAccountsData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query: {
        /**
         * Bc Id
         */
        bc_id: string;
        /**
         * Query
         */
        query?: string;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Remote Status
         */
        remote_status?: string | null;
        /**
         * Availability
         */
        availability?: 'AVAILABLE' | 'PERMISSION_UNKNOWN' | 'NO_ACCESS' | 'OWNERSHIP_CONFLICT' | 'METADATA_INCOMPLETE' | null;
    };
    url: '/api/tenants/{tenant_id}/accounts';
};

export type accountsGetAccountsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsGetAccountsError = accountsGetAccountsErrors[keyof accountsGetAccountsErrors];

export type accountsGetAccountsResponses = {
    /**
     * Successful Response
     */
    200: Page_AccountPublic_;
};

export type accountsGetAccountsResponse = accountsGetAccountsResponses[keyof accountsGetAccountsResponses];

export type accountsPostResolveData = {
    body: ResolveRequest;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/accounts/resolve';
};

export type accountsPostResolveErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsPostResolveError = accountsPostResolveErrors[keyof accountsPostResolveErrors];

export type accountsPostResolveResponses = {
    /**
     * Response Accounts-Post Resolve
     *
     * Successful Response
     */
    200: Array<ResolvedLine>;
};

export type accountsPostResolveResponse = accountsPostResolveResponses[keyof accountsPostResolveResponses];

export type accountsGetBcsData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: {
        /**
         * Query
         */
        query?: string;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Connection Id
         */
        connection_id?: string | null;
    };
    url: '/api/tenants/{tenant_id}/bcs';
};

export type accountsGetBcsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsGetBcsError = accountsGetBcsErrors[keyof accountsGetBcsErrors];

export type accountsGetBcsResponses = {
    /**
     * Successful Response
     */
    200: Page_BCPublic_;
};

export type accountsGetBcsResponse = accountsGetBcsResponses[keyof accountsGetBcsResponses];

export type accountsGetConnectionsData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/tenants/{tenant_id}/tiktok/connections';
};

export type accountsGetConnectionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsGetConnectionsError = accountsGetConnectionsErrors[keyof accountsGetConnectionsErrors];

export type accountsGetConnectionsResponses = {
    /**
     * Successful Response
     */
    200: Page_ConnectionPublic_;
};

export type accountsGetConnectionsResponse = accountsGetConnectionsResponses[keyof accountsGetConnectionsResponses];

export type accountsGetConfigurationData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/tiktok/configuration';
};

export type accountsGetConfigurationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsGetConfigurationError = accountsGetConfigurationErrors[keyof accountsGetConfigurationErrors];

export type accountsGetConfigurationResponses = {
    /**
     * Successful Response
     */
    200: AppConfiguration;
};

export type accountsGetConfigurationResponse = accountsGetConfigurationResponses[keyof accountsGetConfigurationResponses];

export type accountsPostAuthorizationData = {
    body: AuthorizationRequest;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/tiktok/authorizations';
};

export type accountsPostAuthorizationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsPostAuthorizationError = accountsPostAuthorizationErrors[keyof accountsPostAuthorizationErrors];

export type accountsPostAuthorizationResponses = {
    /**
     * Successful Response
     */
    200: AuthorizationURL;
};

export type accountsPostAuthorizationResponse = accountsPostAuthorizationResponses[keyof accountsPostAuthorizationResponses];

export type accountsPatchConnectionData = {
    body: ConnectionUpdate;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/tiktok/connections/{connection_id}';
};

export type accountsPatchConnectionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsPatchConnectionError = accountsPatchConnectionErrors[keyof accountsPatchConnectionErrors];

export type accountsPatchConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionPublic;
};

export type accountsPatchConnectionResponse = accountsPatchConnectionResponses[keyof accountsPatchConnectionResponses];

export type providersPostPreparationData = {
    body: LinkPreparationRequest;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/providers/link-preparations';
};

export type providersPostPreparationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type providersPostPreparationError = providersPostPreparationErrors[keyof providersPostPreparationErrors];

export type providersPostPreparationResponses = {
    /**
     * Successful Response
     */
    202: PreparationAccepted;
};

export type providersPostPreparationResponse = providersPostPreparationResponses[keyof providersPostPreparationResponses];

export type providersGetPreparationData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/tenants/{tenant_id}/providers/link-preparations/{task_id}';
};

export type providersGetPreparationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type providersGetPreparationError = providersGetPreparationErrors[keyof providersGetPreparationErrors];

export type providersGetPreparationResponses = {
    /**
     * Successful Response
     */
    200: Page_ResolvedLink_;
};

export type providersGetPreparationResponse = providersGetPreparationResponses[keyof providersGetPreparationResponses];

export type providersPostCandidateData = {
    body: CandidateSelection;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Input Id
         */
        input_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/providers/inputs/{input_id}/candidate';
};

export type providersPostCandidateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type providersPostCandidateError = providersPostCandidateErrors[keyof providersPostCandidateErrors];

export type providersPostCandidateResponses = {
    /**
     * Successful Response
     */
    202: PreparationAccepted;
};

export type providersPostCandidateResponse = providersPostCandidateResponses[keyof providersPostCandidateResponses];

export type providersListConnectionsData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/tenants/{tenant_id}/providers/connections';
};

export type providersListConnectionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type providersListConnectionsError = providersListConnectionsErrors[keyof providersListConnectionsErrors];

export type providersListConnectionsResponses = {
    /**
     * Successful Response
     */
    200: Page_ProviderConnectionPublic_;
};

export type providersListConnectionsResponse = providersListConnectionsResponses[keyof providersListConnectionsResponses];

export type providersPostConnectionData = {
    body: ProviderConnectionCreate;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/providers/connections';
};

export type providersPostConnectionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type providersPostConnectionError = providersPostConnectionErrors[keyof providersPostConnectionErrors];

export type providersPostConnectionResponses = {
    /**
     * Successful Response
     */
    201: ProviderConnectionPublic;
};

export type providersPostConnectionResponse = providersPostConnectionResponses[keyof providersPostConnectionResponses];

export type providersPatchConnectionData = {
    body: ProviderConnectionUpdate;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/providers/connections/{connection_id}';
};

export type providersPatchConnectionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type providersPatchConnectionError = providersPatchConnectionErrors[keyof providersPatchConnectionErrors];

export type providersPatchConnectionResponses = {
    /**
     * Successful Response
     */
    200: ProviderConnectionPublic;
};

export type providersPatchConnectionResponse = providersPatchConnectionResponses[keyof providersPatchConnectionResponses];

export type providersPostVerifyData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/providers/connections/{connection_id}/verify';
};

export type providersPostVerifyErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type providersPostVerifyError = providersPostVerifyErrors[keyof providersPostVerifyErrors];

export type providersPostVerifyResponses = {
    /**
     * Successful Response
     */
    200: ProviderConnectionPublic;
};

export type providersPostVerifyResponse = providersPostVerifyResponses[keyof providersPostVerifyResponses];

export type providersListApplicationsData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/tenants/{tenant_id}/providers/connections/{connection_id}/applications';
};

export type providersListApplicationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type providersListApplicationsError = providersListApplicationsErrors[keyof providersListApplicationsErrors];

export type providersListApplicationsResponses = {
    /**
     * Successful Response
     */
    200: Page_ProviderApplicationPublic_;
};

export type providersListApplicationsResponse = providersListApplicationsResponses[keyof providersListApplicationsResponses];

export type strategiesGetStrategiesData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: {
        /**
         * Query
         */
        query?: string;
        /**
         * Active
         */
        active?: boolean | null;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/tenants/{tenant_id}/strategies';
};

export type strategiesGetStrategiesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type strategiesGetStrategiesError = strategiesGetStrategiesErrors[keyof strategiesGetStrategiesErrors];

export type strategiesGetStrategiesResponses = {
    /**
     * Successful Response
     */
    200: Page_StrategyPublic_;
};

export type strategiesGetStrategiesResponse = strategiesGetStrategiesResponses[keyof strategiesGetStrategiesResponses];

export type strategiesCreateData = {
    body: CreateStrategyRequest;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/strategies';
};

export type strategiesCreateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type strategiesCreateError = strategiesCreateErrors[keyof strategiesCreateErrors];

export type strategiesCreateResponses = {
    /**
     * Successful Response
     */
    201: StrategyPublic;
};

export type strategiesCreateResponse = strategiesCreateResponses[keyof strategiesCreateResponses];

export type strategiesValidateData = {
    body: StrategyConfig_Input;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/strategies/validate';
};

export type strategiesValidateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type strategiesValidateError = strategiesValidateErrors[keyof strategiesValidateErrors];

export type strategiesValidateResponses = {
    /**
     * Successful Response
     */
    200: ValidationResult;
};

export type strategiesValidateResponse = strategiesValidateResponses[keyof strategiesValidateResponses];

export type strategiesGetOneData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/strategies/{strategy_id}';
};

export type strategiesGetOneErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type strategiesGetOneError = strategiesGetOneErrors[keyof strategiesGetOneErrors];

export type strategiesGetOneResponses = {
    /**
     * Successful Response
     */
    200: StrategyPublic;
};

export type strategiesGetOneResponse = strategiesGetOneResponses[keyof strategiesGetOneResponses];

export type strategiesSetStateData = {
    body: StrategyStateRequest;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/strategies/{strategy_id}';
};

export type strategiesSetStateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type strategiesSetStateError = strategiesSetStateErrors[keyof strategiesSetStateErrors];

export type strategiesSetStateResponses = {
    /**
     * Successful Response
     */
    200: StrategyPublic;
};

export type strategiesSetStateResponse = strategiesSetStateResponses[keyof strategiesSetStateResponses];

export type strategiesVersionsData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/tenants/{tenant_id}/strategies/{strategy_id}/versions';
};

export type strategiesVersionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type strategiesVersionsError = strategiesVersionsErrors[keyof strategiesVersionsErrors];

export type strategiesVersionsResponses = {
    /**
     * Successful Response
     */
    200: Page_VersionPublic_;
};

export type strategiesVersionsResponse = strategiesVersionsResponses[keyof strategiesVersionsResponses];

export type strategiesAppendData = {
    body: AppendVersionRequest;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Strategy Id
         */
        strategy_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/strategies/{strategy_id}/versions';
};

export type strategiesAppendErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type strategiesAppendError = strategiesAppendErrors[keyof strategiesAppendErrors];

export type strategiesAppendResponses = {
    /**
     * Successful Response
     */
    201: VersionPublic;
};

export type strategiesAppendResponse = strategiesAppendResponses[keyof strategiesAppendResponses];

export type strategiesVersionData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/strategy-versions/{version_id}';
};

export type strategiesVersionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type strategiesVersionError = strategiesVersionErrors[keyof strategiesVersionErrors];

export type strategiesVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionPublic;
};

export type strategiesVersionResponse = strategiesVersionResponses[keyof strategiesVersionResponses];

export type strategiesSavedRequestData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/strategy-save-requests/{request_id}';
};

export type strategiesSavedRequestErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type strategiesSavedRequestError = strategiesSavedRequestErrors[keyof strategiesSavedRequestErrors];

export type strategiesSavedRequestResponses = {
    /**
     * Successful Response
     */
    200: VersionPublic;
};

export type strategiesSavedRequestResponse = strategiesSavedRequestResponses[keyof strategiesSavedRequestResponses];

export type strategiesCopyPoolData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/copy-pools/{version_id}';
};

export type strategiesCopyPoolErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type strategiesCopyPoolError = strategiesCopyPoolErrors[keyof strategiesCopyPoolErrors];

export type strategiesCopyPoolResponses = {
    /**
     * Successful Response
     */
    200: CopyPoolPublic;
};

export type strategiesCopyPoolResponse = strategiesCopyPoolResponses[keyof strategiesCopyPoolResponses];
