// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AccountPublic
 */
export type AccountPublic = {
    /**
     * Advertiser Id
     */
    advertiser_id: string;
    /**
     * Bc Id
     */
    bc_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Currency
     */
    currency: string;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Remote Status
     */
    remote_status: string;
    /**
     * Ownership Conflict
     */
    ownership_conflict: boolean;
    /**
     * Can Build
     */
    can_build: boolean;
    /**
     * Can Upload
     */
    can_upload: boolean;
    /**
     * Permission State
     */
    permission_state: string;
    /**
     * Availability
     */
    availability: 'AVAILABLE' | 'PERMISSION_UNKNOWN' | 'NO_ACCESS' | 'OWNERSHIP_CONFLICT' | 'METADATA_INCOMPLETE';
    /**
     * Checked At
     */
    checked_at: string | null;
};

/**
 * AppConfiguration
 */
export type AppConfiguration = {
    /**
     * Code
     */
    code?: string | null;
    /**
     * Configured
     */
    configured: boolean;
    /**
     * Status
     */
    status: 'READY' | 'NOT_CONFIGURED' | 'INCOMPLETE';
    /**
     * Missing Fields
     */
    missing_fields: Array<string>;
};

/**
 * AuthorizationRequest
 */
export type AuthorizationRequest = {
    /**
     * Connection Id
     */
    connection_id?: string | null;
};

/**
 * AuthorizationURL
 */
export type AuthorizationURL = {
    /**
     * Url
     */
    url: string;
};

/**
 * BCPublic
 */
export type BCPublic = {
    /**
     * Bc Id
     */
    bc_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Ownership Conflict
     */
    ownership_conflict: boolean;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ConnectionPublic
 *
 * Explicit allowlist: never serialize ORM credential fields to HTTP.
 */
export type ConnectionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * Status
     */
    status: 'PENDING_AUTH' | 'DISCOVERING' | 'ACTIVE' | 'REAUTH_REQUIRED' | 'ERROR' | 'DISABLED';
    /**
     * Last Discovery
     */
    last_discovery?: string | null;
    /**
     * Last Authorized At
     */
    last_authorized_at?: string | null;
    /**
     * Discovery Status
     */
    discovery_status?: 'QUEUED' | 'RUNNING' | 'ADMISSION_WAIT' | 'ERROR' | 'COMPLETE' | 'CANCELLED' | null;
    /**
     * Error Code
     */
    error_code?: string | null;
};

/**
 * ConnectionUpdate
 */
export type ConnectionUpdate = {
    /**
     * Status
     */
    status: 'DISABLED';
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InputLine
 */
export type InputLine = {
    /**
     * Line No
     */
    line_no: number;
    /**
     * Raw
     */
    raw: string;
};

/**
 * MemberPublic
 */
export type MemberPublic = {
    /**
     * Tenant Id
     */
    tenant_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role: 'tenant_admin' | 'operator' | 'viewer';
    /**
     * Active
     */
    active: boolean;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
    /**
     * User Active
     */
    user_active: boolean;
};

/**
 * MemberSet
 */
export type MemberSet = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role: 'tenant_admin' | 'operator' | 'viewer';
    /**
     * Active
     */
    active: boolean;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * Page[AccountPublic]
 */
export type Page_AccountPublic_ = {
    /**
     * Items
     */
    items: Array<AccountPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[BCPublic]
 */
export type Page_BCPublic_ = {
    /**
     * Items
     */
    items: Array<BCPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[ConnectionPublic]
 */
export type Page_ConnectionPublic_ = {
    /**
     * Items
     */
    items: Array<ConnectionPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[MemberPublic]
 */
export type Page_MemberPublic_ = {
    /**
     * Items
     */
    items: Array<MemberPublic>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[TenantSummary]
 */
export type Page_TenantSummary_ = {
    /**
     * Items
     */
    items: Array<TenantSummary>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * Page[UserCandidate]
 */
export type Page_UserCandidate_ = {
    /**
     * Items
     */
    items: Array<UserCandidate>;
    /**
     * Next Cursor
     */
    next_cursor?: string | null;
};

/**
 * ResolveRequest
 */
export type ResolveRequest = {
    /**
     * Bc Id
     */
    bc_id: string;
    /**
     * Lines
     */
    lines: Array<InputLine>;
};

/**
 * ResolvedLine
 */
export type ResolvedLine = {
    /**
     * Line No
     */
    line_no: number;
    /**
     * Raw
     */
    raw: string;
    /**
     * Status
     */
    status: 'MATCHED' | 'DUPLICATE' | 'AMBIGUOUS' | 'NOT_FOUND' | 'EMPTY' | 'BLOCKED';
    /**
     * Advertiser Id
     */
    advertiser_id?: string | null;
    /**
     * Candidates
     */
    candidates?: Array<string>;
    /**
     * Duplicate Of
     */
    duplicate_of?: number | null;
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * Tenant
 */
export type Tenant = {
    /**
     * Id
     */
    id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Active
     */
    active?: boolean;
};

/**
 * TenantCreate
 */
export type TenantCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Administrator Id
     */
    administrator_id: string;
};

/**
 * TenantSummary
 */
export type TenantSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Active
     */
    active: boolean;
    /**
     * Role
     */
    role: 'platform_admin' | 'tenant_admin' | 'operator' | 'viewer';
};

/**
 * TenantUpdate
 */
export type TenantUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Active
     */
    active?: boolean | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCandidate
 */
export type UserCandidate = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Full Name
     */
    full_name: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type integrationsTiktokCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/tiktok/callback';
};

export type integrationsTiktokCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type tenantsGetPlatformUserCandidatesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * After Id
         */
        after_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/platform/user-candidates';
};

export type tenantsGetPlatformUserCandidatesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsGetPlatformUserCandidatesError = tenantsGetPlatformUserCandidatesErrors[keyof tenantsGetPlatformUserCandidatesErrors];

export type tenantsGetPlatformUserCandidatesResponses = {
    /**
     * Successful Response
     */
    200: Page_UserCandidate_;
};

export type tenantsGetPlatformUserCandidatesResponse = tenantsGetPlatformUserCandidatesResponses[keyof tenantsGetPlatformUserCandidatesResponses];

export type tenantsGetMemberCandidatesData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * After Id
         */
        after_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/tenants/{tenant_id}/member-candidates';
};

export type tenantsGetMemberCandidatesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsGetMemberCandidatesError = tenantsGetMemberCandidatesErrors[keyof tenantsGetMemberCandidatesErrors];

export type tenantsGetMemberCandidatesResponses = {
    /**
     * Successful Response
     */
    200: Page_UserCandidate_;
};

export type tenantsGetMemberCandidatesResponse = tenantsGetMemberCandidatesResponses[keyof tenantsGetMemberCandidatesResponses];

export type tenantsGetMyTenantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * After Id
         */
        after_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string;
        /**
         * Active
         */
        active?: boolean | null;
    };
    url: '/api/me/tenants';
};

export type tenantsGetMyTenantsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsGetMyTenantsError = tenantsGetMyTenantsErrors[keyof tenantsGetMyTenantsErrors];

export type tenantsGetMyTenantsResponses = {
    /**
     * Successful Response
     */
    200: Page_TenantSummary_;
};

export type tenantsGetMyTenantsResponse = tenantsGetMyTenantsResponses[keyof tenantsGetMyTenantsResponses];

export type tenantsGetPlatformTenantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * After Id
         */
        after_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string;
        /**
         * Active
         */
        active?: boolean | null;
    };
    url: '/api/platform/tenants';
};

export type tenantsGetPlatformTenantsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsGetPlatformTenantsError = tenantsGetPlatformTenantsErrors[keyof tenantsGetPlatformTenantsErrors];

export type tenantsGetPlatformTenantsResponses = {
    /**
     * Successful Response
     */
    200: Page_TenantSummary_;
};

export type tenantsGetPlatformTenantsResponse = tenantsGetPlatformTenantsResponses[keyof tenantsGetPlatformTenantsResponses];

export type tenantsPostTenantData = {
    body: TenantCreate;
    path?: never;
    query?: never;
    url: '/api/platform/tenants';
};

export type tenantsPostTenantErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsPostTenantError = tenantsPostTenantErrors[keyof tenantsPostTenantErrors];

export type tenantsPostTenantResponses = {
    /**
     * Successful Response
     */
    201: Tenant;
};

export type tenantsPostTenantResponse = tenantsPostTenantResponses[keyof tenantsPostTenantResponses];

export type tenantsPatchTenantData = {
    body: TenantUpdate;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/platform/tenants/{tenant_id}';
};

export type tenantsPatchTenantErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsPatchTenantError = tenantsPatchTenantErrors[keyof tenantsPatchTenantErrors];

export type tenantsPatchTenantResponses = {
    /**
     * Successful Response
     */
    200: Tenant;
};

export type tenantsPatchTenantResponse = tenantsPatchTenantResponses[keyof tenantsPatchTenantResponses];

export type tenantsGetMembersData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: {
        /**
         * After Id
         */
        after_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string;
        /**
         * Role
         */
        role?: 'tenant_admin' | 'operator' | 'viewer' | null;
        /**
         * Active
         */
        active?: boolean | null;
    };
    url: '/api/tenants/{tenant_id}/members';
};

export type tenantsGetMembersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsGetMembersError = tenantsGetMembersErrors[keyof tenantsGetMembersErrors];

export type tenantsGetMembersResponses = {
    /**
     * Successful Response
     */
    200: Page_MemberPublic_;
};

export type tenantsGetMembersResponse = tenantsGetMembersResponses[keyof tenantsGetMembersResponses];

export type tenantsPutMemberData = {
    body: MemberSet;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/members';
};

export type tenantsPutMemberErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tenantsPutMemberError = tenantsPutMemberErrors[keyof tenantsPutMemberErrors];

export type tenantsPutMemberResponses = {
    /**
     * Successful Response
     */
    200: MemberPublic;
};

export type tenantsPutMemberResponse = tenantsPutMemberResponses[keyof tenantsPutMemberResponses];

export type accountsGetAccountsData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query: {
        /**
         * Bc Id
         */
        bc_id: string;
        /**
         * Query
         */
        query?: string;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Remote Status
         */
        remote_status?: string | null;
        /**
         * Availability
         */
        availability?: 'AVAILABLE' | 'PERMISSION_UNKNOWN' | 'NO_ACCESS' | 'OWNERSHIP_CONFLICT' | 'METADATA_INCOMPLETE' | null;
    };
    url: '/api/tenants/{tenant_id}/accounts';
};

export type accountsGetAccountsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsGetAccountsError = accountsGetAccountsErrors[keyof accountsGetAccountsErrors];

export type accountsGetAccountsResponses = {
    /**
     * Successful Response
     */
    200: Page_AccountPublic_;
};

export type accountsGetAccountsResponse = accountsGetAccountsResponses[keyof accountsGetAccountsResponses];

export type accountsPostResolveData = {
    body: ResolveRequest;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/accounts/resolve';
};

export type accountsPostResolveErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsPostResolveError = accountsPostResolveErrors[keyof accountsPostResolveErrors];

export type accountsPostResolveResponses = {
    /**
     * Response Accounts-Post Resolve
     *
     * Successful Response
     */
    200: Array<ResolvedLine>;
};

export type accountsPostResolveResponse = accountsPostResolveResponses[keyof accountsPostResolveResponses];

export type accountsGetBcsData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: {
        /**
         * Query
         */
        query?: string;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Connection Id
         */
        connection_id?: string | null;
    };
    url: '/api/tenants/{tenant_id}/bcs';
};

export type accountsGetBcsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsGetBcsError = accountsGetBcsErrors[keyof accountsGetBcsErrors];

export type accountsGetBcsResponses = {
    /**
     * Successful Response
     */
    200: Page_BCPublic_;
};

export type accountsGetBcsResponse = accountsGetBcsResponses[keyof accountsGetBcsResponses];

export type accountsGetConnectionsData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: {
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: string | null;
    };
    url: '/api/tenants/{tenant_id}/tiktok/connections';
};

export type accountsGetConnectionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsGetConnectionsError = accountsGetConnectionsErrors[keyof accountsGetConnectionsErrors];

export type accountsGetConnectionsResponses = {
    /**
     * Successful Response
     */
    200: Page_ConnectionPublic_;
};

export type accountsGetConnectionsResponse = accountsGetConnectionsResponses[keyof accountsGetConnectionsResponses];

export type accountsGetConfigurationData = {
    body?: never;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/tiktok/configuration';
};

export type accountsGetConfigurationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsGetConfigurationError = accountsGetConfigurationErrors[keyof accountsGetConfigurationErrors];

export type accountsGetConfigurationResponses = {
    /**
     * Successful Response
     */
    200: AppConfiguration;
};

export type accountsGetConfigurationResponse = accountsGetConfigurationResponses[keyof accountsGetConfigurationResponses];

export type accountsPostAuthorizationData = {
    body: AuthorizationRequest;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/tiktok/authorizations';
};

export type accountsPostAuthorizationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsPostAuthorizationError = accountsPostAuthorizationErrors[keyof accountsPostAuthorizationErrors];

export type accountsPostAuthorizationResponses = {
    /**
     * Successful Response
     */
    200: AuthorizationURL;
};

export type accountsPostAuthorizationResponse = accountsPostAuthorizationResponses[keyof accountsPostAuthorizationResponses];

export type accountsPatchConnectionData = {
    body: ConnectionUpdate;
    path: {
        /**
         * Tenant Id
         */
        tenant_id: string;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/tenants/{tenant_id}/tiktok/connections/{connection_id}';
};

export type accountsPatchConnectionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type accountsPatchConnectionError = accountsPatchConnectionErrors[keyof accountsPatchConnectionErrors];

export type accountsPatchConnectionResponses = {
    /**
     * Successful Response
     */
    200: ConnectionPublic;
};

export type accountsPatchConnectionResponse = accountsPatchConnectionResponses[keyof accountsPatchConnectionResponses];
