"""materials

Revision ID: 0004_materials
Revises: 0003_provider_links
Create Date: 2026-09-09 03:56:24.331227

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0004_materials"
down_revision = "0003_provider_links"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material_file",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("file_name", sa.String(length=1000, collation="C"), nullable=False),
        sa.Column(
            "file_name_folded", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "object_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column(
            "video_md5", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.Column(
            "mime_type", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("storage_state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "storage_state IN ('receiving','stored','unavailable')",
            name="ck_material_storage",
        ),
        sa.CheckConstraint("byte_size > 0", name="ck_material_size"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id"],
            ["tenant_bc.tenant_id", "tenant_bc.bc_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
        sa.UniqueConstraint(
            "tenant_id", "bc_id", "id", name="uq_material_tenant_bc_id"
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uq_material_tenant_id"),
    )
    op.create_index(
        "ix_material_folded_trgm",
        "material_file",
        ["file_name_folded"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"file_name_folded": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_material_tenant_bc_name_id",
        "material_file",
        ["tenant_id", "bc_id", "file_name", "id"],
        unique=False,
    )
    op.create_table(
        "upload_batch",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "request_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id"],
            ["tenant_bc.tenant_id", "tenant_bc.bc_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "bc_id", "id", name="uq_upload_batch_scope"),
        sa.UniqueConstraint("tenant_id", "request_id", name="uq_upload_batch_request"),
    )
    op.create_table(
        "material_asset_operation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempt_token", sa.Uuid(), nullable=True),
        sa.Column("claimed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "request_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "remote_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            "path IN ('upload_original','share_source')",
            name="ck_material_operation_path",
        ),
        sa.CheckConstraint(
            "status != 'sending' OR attempt_token IS NOT NULL",
            name="ck_material_operation_claim",
        ),
        sa.CheckConstraint(
            "status IN ('pending','sending','result_unknown','verifying','confirmed_absent','succeeded','failed')",
            name="ck_material_operation_status",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "material_id"],
            ["material_file.tenant_id", "material_file.bc_id", "material_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "bc_id",
            "material_id",
            "advertiser_id",
            "id",
            name="uq_asset_operation_identity",
        ),
    )
    op.create_index(
        "uq_material_unverified_operation",
        "material_asset_operation",
        ["tenant_id", "material_id", "advertiser_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('pending','sending','result_unknown','verifying','confirmed_absent')"
        ),
    )
    op.create_table(
        "object_upload",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("s3_upload_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "object_key", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False
        ),
        sa.Column("expected_size", sa.BigInteger(), nullable=False),
        sa.Column("part_size", sa.BigInteger(), nullable=False),
        sa.Column("parts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.CheckConstraint(
            "expected_size > 0 AND part_size > 0", name="ck_object_upload_size"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "batch_id"],
            ["upload_batch.tenant_id", "upload_batch.bc_id", "upload_batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "material_id"],
            ["material_file.tenant_id", "material_file.bc_id", "material_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "material_id", name="uq_object_upload_material"
        ),
    )
    op.create_table(
        "account_material",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("video_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cover_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status != 'available' OR (video_id <> '' AND verified_at IS NOT NULL)",
            name="ck_account_material_verified",
        ),
        sa.CheckConstraint(
            "status IN ('available','unavailable','result_unknown')",
            name="ck_account_material_status",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "advertiser_id", "connection_id"],
            [
                "bc_account_access.tenant_id",
                "bc_account_access.bc_id",
                "bc_account_access.advertiser_id",
                "bc_account_access.connection_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "material_id"],
            ["material_file.tenant_id", "material_file.bc_id", "material_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "bc_id",
            "material_id",
            "id",
            name="uq_account_material_identity",
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "material_id",
            "advertiser_id",
            name="uq_account_material_target",
        ),
    )
    op.create_table(
        "material_upload_attempt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "request_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "remote_response", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "advertiser_id", "connection_id"],
            [
                "bc_account_access.tenant_id",
                "bc_account_access.bc_id",
                "bc_account_access.advertiser_id",
                "bc_account_access.connection_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "material_id", "advertiser_id", "operation_id"],
            [
                "material_asset_operation.tenant_id",
                "material_asset_operation.bc_id",
                "material_asset_operation.material_id",
                "material_asset_operation.advertiser_id",
                "material_asset_operation.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "material_id"],
            ["material_file.tenant_id", "material_file.bc_id", "material_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_upload_attempt_material",
        "material_upload_attempt",
        ["tenant_id", "material_id", "id"],
        unique=False,
    )
    op.create_table(
        "material_distribution",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("source_asset_id", sa.Uuid(), nullable=True),
        sa.Column("operation_id", sa.Uuid(), nullable=True),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','preparing','verifying','ready','blocked','result_unknown')",
            name="ck_material_distribution_status",
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "material_id", "advertiser_id", "operation_id"],
            [
                "material_asset_operation.tenant_id",
                "material_asset_operation.bc_id",
                "material_asset_operation.material_id",
                "material_asset_operation.advertiser_id",
                "material_asset_operation.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "material_id", "source_asset_id"],
            [
                "account_material.tenant_id",
                "account_material.bc_id",
                "account_material.material_id",
                "account_material.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "material_id"],
            ["material_file.tenant_id", "material_file.bc_id", "material_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_material_pending_distribution",
        "material_distribution",
        ["tenant_id", "material_id", "advertiser_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('queued','preparing','verifying','result_unknown')"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_material_pending_distribution",
        table_name="material_distribution",
        postgresql_where=sa.text(
            "status IN ('queued','preparing','verifying','result_unknown')"
        ),
    )
    op.drop_table("material_distribution")
    op.drop_index("ix_upload_attempt_material", table_name="material_upload_attempt")
    op.drop_table("material_upload_attempt")
    op.drop_table("account_material")
    op.drop_table("object_upload")
    op.drop_index(
        "uq_material_unverified_operation",
        table_name="material_asset_operation",
        postgresql_where=sa.text(
            "status IN ('pending','sending','result_unknown','verifying','confirmed_absent')"
        ),
    )
    op.drop_table("material_asset_operation")
    op.drop_table("upload_batch")
    op.drop_index("ix_material_tenant_bc_name_id", table_name="material_file")
    op.drop_index(
        "ix_material_folded_trgm",
        table_name="material_file",
        postgresql_using="gin",
        postgresql_ops={"file_name_folded": "gin_trgm_ops"},
    )
    op.drop_table("material_file")
    # ### end Alembic commands ###
