"""persist link free BC capability evidence

Revision ID: 0005e_account_capabilities
Revises: 0005d_build_previews
Create Date: 2026-09-09 06:34:55.497461

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "0005e_account_capabilities"
down_revision = "0005d_build_previews"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_capability_job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("credential_version", sa.Integer(), nullable=False),
        sa.Column(
            "directory_basis",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("next_page", sa.Integer(), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column("total_count", sa.Integer(), nullable=True),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column(
            "publish_after", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("published_count", sa.Integer(), nullable=False),
        sa.Column("scope_known", sa.Boolean(), nullable=False),
        sa.Column("scope_build", sa.Boolean(), nullable=False),
        sa.Column("scope_upload", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("dispatch_id", sa.Uuid(), nullable=True),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("claimed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("repair_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "error_code", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "phase IN ('READ','PUBLISH','DONE')", name="ck_capability_phase"
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','COMPLETE','BLOCKED','STALE','FAILED')",
            name="ck_capability_status",
        ),
        sa.CheckConstraint(
            "(claim_token IS NULL) = (claimed_until IS NULL)",
            name="ck_capability_claim",
        ),
        sa.CheckConstraint(
            "credential_version >= 0 AND revision >= 0 AND next_page > 0 AND seen_count >= 0 AND published_count >= 0 AND failure_count >= 0",
            name="ck_capability_counters",
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id"],
            ["tenant_bc.tenant_id", "tenant_bc.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id"],
            ["tiktok_connection.tenant_id", "tiktok_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "bc_id", "id", name="uq_capability_job_scope"),
    )
    op.create_index(
        "ix_capability_repair",
        "account_capability_job",
        ["status", "repair_after", "id"],
        unique=False,
    )
    op.create_index(
        "uq_capability_active_basis",
        "account_capability_job",
        [
            "tenant_id",
            "bc_id",
            "connection_id",
            "credential_version",
            "directory_basis",
        ],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "account_capability_page",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "page > 0 AND row_count BETWEEN 0 AND 50", name="ck_capability_page"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "job_id"],
            [
                "account_capability_job.tenant_id",
                "account_capability_job.bc_id",
                "account_capability_job.id",
            ],
        ),
        sa.PrimaryKeyConstraint("job_id", "page"),
    )
    op.create_table(
        "account_capability_request",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "job_id"],
            [
                "account_capability_job.tenant_id",
                "account_capability_job.bc_id",
                "account_capability_job.id",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "bc_id", "request_id"),
    )
    op.create_table(
        "account_capability_asset",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.CheckConstraint(
            "role IN ('ADMIN','OPERATOR','ANALYST')", name="ck_capability_asset_role"
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "page"],
            ["account_capability_page.job_id", "account_capability_page.page"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "job_id"],
            [
                "account_capability_job.tenant_id",
                "account_capability_job.bc_id",
                "account_capability_job.id",
            ],
        ),
        sa.PrimaryKeyConstraint("job_id", "advertiser_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account_capability_asset")
    op.drop_table("account_capability_request")
    op.drop_table("account_capability_page")
    op.drop_index(
        "uq_capability_active_basis",
        table_name="account_capability_job",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index("ix_capability_repair", table_name="account_capability_job")
    op.drop_table("account_capability_job")
    # ### end Alembic commands ###
