"""immutable strategy versions

Revision ID: 0005_strategies
Revises: 0004c_object_claims
Create Date: 2026-09-09 04:36:12.696686

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql
from datetime import UTC, datetime
from uuid import UUID, uuid5

# revision identifiers, used by Alembic.
revision = "0005_strategies"
down_revision = "0004c_object_claims"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "copy_pool_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("sealed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "copy_entry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pool_version_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.CheckConstraint("position > 0", name="ck_copy_position"),
        sa.ForeignKeyConstraint(
            ["pool_version_id"],
            ["copy_pool_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pool_version_id", "position"),
        sa.UniqueConstraint("pool_version_id", "text"),
    )
    op.create_index(
        op.f("ix_copy_entry_pool_version_id"),
        "copy_entry",
        ["pool_version_id"],
        unique=False,
    )
    op.create_table(
        "strategy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("latest_version", sa.Integer(), nullable=False),
        sa.CheckConstraint("latest_version >= 0", name="ck_strategy_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_strategy_tenant_id"),
    )
    op.create_index(
        "ix_strategy_tenant_page", "strategy", ["tenant_id", "id"], unique=False
    )
    op.create_table(
        "strategy_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("copy_pool_version_id", sa.Uuid(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("budget", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("target_roas", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "request_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "request_kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.CheckConstraint(
            "coalesce((jsonb_typeof(config) = 'object' AND (config->>'budget')::numeric = budget AND (config->>'target_roas')::numeric = target_roas AND config->>'copy_pool_version' = copy_pool_version_id::text), false)",
            name="ck_strategy_config_identity",
        ),
        sa.CheckConstraint(
            "request_kind IN ('create','append')", name="ck_strategy_request_kind"
        ),
        sa.CheckConstraint(
            "number > 0 AND budget > 0 AND target_roas > 0 AND budget != 'NaN'::numeric AND target_roas != 'NaN'::numeric",
            name="ck_strategy_version_values",
        ),
        sa.ForeignKeyConstraint(
            ["copy_pool_version_id"],
            ["copy_pool_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "strategy_id"],
            ["strategy.tenant_id", "strategy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_strategy_version_tenant_id"),
        sa.UniqueConstraint(
            "tenant_id", "request_id", name="uq_strategy_version_request"
        ),
        sa.UniqueConstraint(
            "tenant_id", "strategy_id", "number", name="uq_strategy_version_number"
        ),
    )
    # Versioned seed lives in this migration, independent of mutable app code.
    pool_id = UUID("02a4e656-a330-40dc-864c-26e81961f3ca")
    pool = sa.table(
        "copy_pool_version",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("sealed", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    entries = sa.table(
        "copy_entry",
        sa.column("id", sa.Uuid()),
        sa.column("pool_version_id", sa.Uuid()),
        sa.column("position", sa.Integer()),
        sa.column("text", sa.String()),
        sa.column("enabled", sa.Boolean()),
    )
    op.bulk_insert(
        pool,
        [
            dict(
                id=pool_id,
                name="通用英文短剧文案 v1",
                sealed=True,
                created_at=datetime(2026, 9, 8, tzinfo=UTC),
            )
        ],
    )
    openers = (
        "A story for your next break.",
        "Your next short drama awaits.",
        "Make room for a little drama.",
        "Take a moment for a new story.",
        "Enjoy a story one episode at a time.",
        "Discover a short drama today.",
        "Add a new story to your day.",
        "Spend a little time with a new drama.",
        "There is a story ready to explore.",
        "Start your next drama break.",
    )
    endings = (
        "Watch an episode.",
        "Start watching today.",
        "See where the story goes.",
        "Discover what happens next.",
        "Take a look at the story.",
        "Follow the story from here.",
        "Find a moment to watch.",
        "Explore the next scene.",
        "Let the story unfold.",
        "Begin with one episode.",
    )
    texts = [f"{start} {end}" for start in openers for end in endings]
    op.bulk_insert(
        entries,
        [
            dict(
                id=uuid5(pool_id, value),
                pool_version_id=pool_id,
                position=position,
                text=value,
                enabled=True,
            )
            for position, value in enumerate(texts, 1)
        ],
    )
    op.execute("""CREATE FUNCTION reject_strategy_version_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'strategy versions are immutable' USING ERRCODE = '23514'; END; $$""")
    op.execute(
        "CREATE TRIGGER strategy_version_immutable BEFORE UPDATE OR DELETE ON strategy_version FOR EACH ROW EXECUTE FUNCTION reject_strategy_version_mutation()"
    )
    op.execute("""CREATE FUNCTION guard_copy_pool_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF OLD.sealed THEN RAISE EXCEPTION 'copy pool versions are immutable' USING ERRCODE = '23514'; END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END; $$""")
    op.execute(
        "CREATE TRIGGER copy_pool_immutable BEFORE UPDATE OR DELETE ON copy_pool_version FOR EACH ROW EXECUTE FUNCTION guard_copy_pool_mutation()"
    )
    op.execute("""CREATE FUNCTION guard_copy_entry_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE is_sealed boolean;
    BEGIN
      IF TG_OP != 'INSERT' THEN RAISE EXCEPTION 'copy entries are immutable' USING ERRCODE = '23514'; END IF;
      SELECT sealed INTO is_sealed FROM copy_pool_version WHERE id = NEW.pool_version_id FOR SHARE;
      IF is_sealed THEN RAISE EXCEPTION 'copy pool is sealed' USING ERRCODE = '23514'; END IF;
      RETURN NEW;
    END; $$""")
    op.execute(
        "CREATE TRIGGER copy_entry_immutable BEFORE INSERT OR UPDATE OR DELETE ON copy_entry FOR EACH ROW EXECUTE FUNCTION guard_copy_entry_mutation()"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("strategy_version")
    op.drop_index("ix_strategy_tenant_page", table_name="strategy")
    op.drop_table("strategy")
    op.drop_index(op.f("ix_copy_entry_pool_version_id"), table_name="copy_entry")
    op.drop_table("copy_entry")
    op.drop_table("copy_pool_version")
    op.execute("DROP FUNCTION guard_copy_entry_mutation()")
    op.execute("DROP FUNCTION guard_copy_pool_mutation()")
    op.execute("DROP FUNCTION reject_strategy_version_mutation()")
    # ### end Alembic commands ###
