"""freeze bounded advertising previews

Revision ID: 0005d_build_previews
Revises: 0005c_scene_facts
Create Date: 2026-09-09 06:18:02.151455

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0005d_build_previews"
down_revision = "0005c_scene_facts"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build_preview",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("draft_revision", sa.Integer(), nullable=False),
        sa.Column("strategy_version_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "batch_short_id",
            sqlmodel.sql.sqltypes.AutoString(length=32),
            nullable=False,
        ),
        sa.Column(
            "local_date", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("budget", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("target_roas", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "content_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("dispatch_id", sa.Uuid(), nullable=True),
        sa.Column("repair_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('BUILDING','FROZEN','OBSOLETE','FAILED')",
            name="ck_preview_status",
        ),
        sa.CheckConstraint(
            "draft_revision > 0 AND generation >= 0", name="ck_preview_revision"
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dispatch_id"],
            ["pending_dispatch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "draft_id", "bc_id"],
            ["build_draft.tenant_id", "build_draft.id", "build_draft.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "strategy_version_id"],
            ["strategy_version.tenant_id", "strategy_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_short_id", name="uq_preview_batch_short"),
        sa.UniqueConstraint(
            "tenant_id", "draft_id", "draft_revision", name="uq_preview_revision"
        ),
        sa.UniqueConstraint("tenant_id", "id", "bc_id", name="uq_preview_bc"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_preview_tenant"),
    )
    op.create_index(
        "ix_preview_repair",
        "build_preview",
        ["status", "repair_after", "id"],
        unique=False,
    )
    op.create_table(
        "preview_drama",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("drama_id", sa.Uuid(), nullable=False),
        sa.Column("link_id", sa.Uuid(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("protected_base", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "drama_id"],
            ["provider_drama.tenant_id", "provider_drama.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "link_id"],
            ["promotion_link.tenant_id", "promotion_link.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "bc_id"],
            ["build_preview.tenant_id", "build_preview.id", "build_preview.bc_id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "preview_id", "drama_id"),
    )
    op.create_table(
        "preview_input",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column(
            "raw_text", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("reason_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("duplicate_of", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('account','drama') AND line_no > 0", name="ck_preview_input"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "bc_id"],
            ["build_preview.tenant_id", "build_preview.id", "build_preview.bc_id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "preview_id", "kind", "line_no"),
    )
    op.create_table(
        "build_unit",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("drama_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False
        ),
        sa.Column(
            "timezone", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("campaign_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "campaign_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("readiness", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "scene_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("group_count", sa.Integer(), nullable=False),
        sa.Column("ad_count", sa.Integer(), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "readiness IN ('READY','PREPARING','BLOCKED')",
            name="ck_build_unit_readiness",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "advertiser_id", "connection_id"],
            [
                "bc_account_access.tenant_id",
                "bc_account_access.bc_id",
                "bc_account_access.advertiser_id",
                "bc_account_access.connection_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "bc_id"],
            ["build_preview.tenant_id", "build_preview.id", "build_preview.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "drama_id"],
            [
                "preview_drama.tenant_id",
                "preview_drama.preview_id",
                "preview_drama.drama_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "id", "preview_id", "bc_id", name="uq_build_unit_preview"
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uq_build_unit_tenant"),
        sa.UniqueConstraint(
            "tenant_id",
            "preview_id",
            "drama_id",
            "advertiser_id",
            name="uq_build_unit_pair",
        ),
    )
    op.create_index(
        "ix_build_unit_names",
        "build_unit",
        ["tenant_id", "preview_id", "advertiser_id", "campaign_digest"],
        unique=False,
    )
    op.create_table(
        "preview_drama_group",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("drama_id", sa.Uuid(), nullable=False),
        sa.Column("group_no", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("group_no > 0", name="ck_preview_group_no"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "bc_id"],
            ["build_preview.tenant_id", "build_preview.id", "build_preview.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "drama_id"],
            [
                "preview_drama.tenant_id",
                "preview_drama.preview_id",
                "preview_drama.drama_id",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "preview_id", "drama_id", "group_no"),
        sa.UniqueConstraint(
            "tenant_id", "preview_id", "id", name="uq_preview_drama_group_id"
        ),
    )
    op.create_table(
        "planned_group",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("drama_id", sa.Uuid(), nullable=False),
        sa.Column("group_no", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "bc_id"],
            ["build_preview.tenant_id", "build_preview.id", "build_preview.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "drama_id", "group_no"],
            [
                "preview_drama_group.tenant_id",
                "preview_drama_group.preview_id",
                "preview_drama_group.drama_id",
                "preview_drama_group.group_no",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "unit_id", "preview_id", "bc_id"],
            [
                "build_unit.tenant_id",
                "build_unit.id",
                "build_unit.preview_id",
                "build_unit.bc_id",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "preview_id", "id"),
        sa.UniqueConstraint(
            "tenant_id", "unit_id", "group_no", name="uq_planned_group_no"
        ),
    )
    op.create_table(
        "preview_copy",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("drama_id", sa.Uuid(), nullable=False),
        sa.Column("group_no", sa.Integer(), nullable=False),
        sa.Column("creative_no", sa.Integer(), nullable=False),
        sa.Column("copy_id", sa.Uuid(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint("creative_no > 0", name="ck_preview_copy_no"),
        sa.ForeignKeyConstraint(
            ["copy_id"],
            ["copy_entry.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "bc_id"],
            ["build_preview.tenant_id", "build_preview.id", "build_preview.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "drama_id", "group_no"],
            [
                "preview_drama_group.tenant_id",
                "preview_drama_group.preview_id",
                "preview_drama_group.drama_id",
                "preview_drama_group.group_no",
            ],
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "preview_id", "drama_id", "group_no", "creative_no"
        ),
    )
    op.create_table(
        "preview_group_material",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("drama_id", sa.Uuid(), nullable=False),
        sa.Column("group_no", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("position > 0", name="ck_preview_material_position"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "material_id"],
            ["material_file.tenant_id", "material_file.bc_id", "material_file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "bc_id"],
            ["build_preview.tenant_id", "build_preview.id", "build_preview.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "drama_id", "group_no"],
            [
                "preview_drama_group.tenant_id",
                "preview_drama_group.preview_id",
                "preview_drama_group.drama_id",
                "preview_drama_group.group_no",
            ],
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "preview_id", "drama_id", "group_no", "position"
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "preview_id",
            "drama_id",
            "material_id",
            name="uq_preview_drama_material",
        ),
    )
    op.create_table(
        "planned_ad",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("creative_no", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("copy_id", sa.Uuid(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "cta_option_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint("creative_no > 0", name="ck_planned_ad_no"),
        sa.ForeignKeyConstraint(
            ["copy_id"],
            ["copy_entry.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "bc_id"],
            ["build_preview.tenant_id", "build_preview.id", "build_preview.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "group_id"],
            ["planned_group.tenant_id", "planned_group.preview_id", "planned_group.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "preview_id", "id"),
        sa.UniqueConstraint(
            "tenant_id", "group_id", "creative_no", name="uq_planned_ad_no"
        ),
    )
    # ### end Alembic commands ###

    op.execute("""
      CREATE FUNCTION check_preview_child_write() RETURNS trigger LANGUAGE plpgsql AS $$
      DECLARE identity uuid; tenant uuid; current_status text;
      BEGIN
        IF TG_OP = 'DELETE' THEN identity := OLD.preview_id; tenant := OLD.tenant_id;
        ELSE identity := NEW.preview_id; tenant := NEW.tenant_id; END IF;
        IF TG_OP = 'UPDATE' AND (OLD.preview_id <> NEW.preview_id OR OLD.tenant_id <> NEW.tenant_id) THEN
          RAISE EXCEPTION 'preview identity is immutable';
        END IF;
        SELECT status INTO current_status FROM build_preview
        WHERE id=identity AND tenant_id=tenant FOR SHARE;
        IF current_status IS DISTINCT FROM 'BUILDING' THEN
          RAISE EXCEPTION 'frozen preview is immutable';
        END IF;
        IF TG_OP='DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
      END $$;
      CREATE FUNCTION check_preview_header_write() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        IF TG_OP='DELETE' THEN RAISE EXCEPTION 'preview is retained'; END IF;
        IF OLD.status <> 'BUILDING' AND NOT (
          OLD.status='FROZEN' AND NEW.status='OBSOLETE' AND
          (to_jsonb(OLD)-'status')=(to_jsonb(NEW)-'status')
        ) THEN RAISE EXCEPTION 'frozen preview header is immutable'; END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER preview_header_frozen BEFORE UPDATE OR DELETE ON build_preview
        FOR EACH ROW EXECUTE FUNCTION check_preview_header_write();
      CREATE FUNCTION obsolete_draft_previews() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        IF NEW.revision <> OLD.revision THEN
          UPDATE build_preview SET status='OBSOLETE' WHERE tenant_id=NEW.tenant_id
            AND draft_id=NEW.id AND draft_revision<>NEW.revision AND status IN ('BUILDING','FROZEN');
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER draft_preview_revision AFTER UPDATE OF revision ON build_draft
        FOR EACH ROW EXECUTE FUNCTION obsolete_draft_previews();
    """)
    for table in (
        "preview_input",
        "preview_drama",
        "preview_drama_group",
        "preview_group_material",
        "preview_copy",
        "build_unit",
        "planned_group",
        "planned_ad",
    ):
        op.execute(
            f"CREATE TRIGGER {table}_frozen BEFORE INSERT OR UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION check_preview_child_write()"
        )


def downgrade():
    op.execute("DROP TRIGGER draft_preview_revision ON build_draft")
    op.execute("DROP FUNCTION obsolete_draft_previews()")
    op.execute("DROP TRIGGER preview_header_frozen ON build_preview")
    op.execute("DROP FUNCTION check_preview_header_write()")
    for table in (
        "preview_input",
        "preview_drama",
        "preview_drama_group",
        "preview_group_material",
        "preview_copy",
        "build_unit",
        "planned_group",
        "planned_ad",
    ):
        op.execute(f"DROP TRIGGER {table}_frozen ON {table}")
    op.execute("DROP FUNCTION check_preview_child_write()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("planned_ad")
    op.drop_table("preview_group_material")
    op.drop_table("preview_copy")
    op.drop_table("planned_group")
    op.drop_table("preview_drama_group")
    op.drop_index("ix_build_unit_names", table_name="build_unit")
    op.drop_table("build_unit")
    op.drop_table("preview_input")
    op.drop_table("preview_drama")
    op.drop_index("ix_preview_repair", table_name="build_preview")
    op.drop_table("build_preview")
    # ### end Alembic commands ###
