"""preserve original draft edit request results

Revision ID: 0005f_draft_mutations
Revises: 0005e_account_capabilities
Create Date: 2026-09-09 06:49:09.308994

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "0005f_draft_mutations"
down_revision = "0005e_account_capabilities"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "draft_mutation_request",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column(
            "request_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("applied_revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('update','groups') AND applied_revision > 0",
            name="ck_draft_mutation_result",
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "draft_id"],
            ["build_draft.tenant_id", "build_draft.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "request_id"),
    )
    # ### end Alembic commands ###

    op.execute("""
      CREATE FUNCTION retain_draft_mutation_result() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN RAISE EXCEPTION 'draft mutation results are immutable'; END $$;
      CREATE TRIGGER draft_mutation_result_immutable BEFORE UPDATE OR DELETE ON draft_mutation_request
      FOR EACH ROW EXECUTE FUNCTION retain_draft_mutation_result();
    """)


def downgrade():
    op.execute("DROP TRIGGER IF EXISTS draft_mutation_result_immutable ON draft_mutation_request")
    op.execute("DROP FUNCTION IF EXISTS retain_draft_mutation_result()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("draft_mutation_request")
    # ### end Alembic commands ###
