"""fenced tenant scene evidence

Revision ID: 0005c_scene_facts
Revises: 0005b_build_drafts
Create Date: 2026-09-09 05:59:01.355620

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0005c_scene_facts"
down_revision = "0005b_build_drafts"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scene_read_state",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("link_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "resource", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "basis_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("generation", sa.Uuid(), nullable=False),
        sa.Column("attempt_token", sa.Uuid(), nullable=True),
        sa.Column("claimed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_page", sa.Integer(), nullable=False),
        sa.Column("last_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "error_code", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.CheckConstraint(
            "resource IN ('account_roles','identity','minis','cta','vbo')",
            name="ck_scene_resource",
        ),
        sa.CheckConstraint("next_page > 0", name="ck_scene_page"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id"],
            ["tenant_bc.tenant_id", "tenant_bc.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id"],
            ["tiktok_connection.tenant_id", "tiktok_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "link_id"],
            ["promotion_link.tenant_id", "promotion_link.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "bc_id",
            "advertiser_id",
            "link_id",
            "resource",
            name="uq_scene_state_scope",
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uq_scene_state_tenant"),
    )
    op.create_table(
        "scene_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("generation", sa.Uuid(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column(
            "endpoint", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "request_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column(
            "source_revision",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column(
            "basis_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("page > 0", name="ck_scene_evidence_page"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "state_id"],
            ["scene_read_state.tenant_id", "scene_read_state.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "state_id", "generation", "page", name="uq_scene_evidence_page"
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uq_scene_evidence_tenant"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scene_evidence")
    op.drop_table("scene_read_state")
    # ### end Alembic commands ###
