"""Persist bounded submissions and immutable execution evidence."""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

revision = "0006_build_execution"
down_revision = "0005f_draft_mutations"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build_submission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expanded", sa.Boolean(), nullable=False),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dispatch_revision", sa.Integer(), nullable=False),
        sa.Column("dispatch_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("repair_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('QUEUED','RUNNING','COMPLETED','PARTIAL','FAILED','NEEDS_REVIEW')",
            name="ck_submission_status",
        ),
        sa.CheckConstraint(
            "dispatch_revision >= 0 AND ordinal > 0", name="ck_submission_revision"
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dispatch_id"],
            ["pending_dispatch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "draft_id", "bc_id"],
            ["build_draft.tenant_id", "build_draft.id", "build_draft.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "bc_id"],
            ["build_preview.tenant_id", "build_preview.id", "build_preview.bc_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "draft_id", "ordinal", name="uq_submission_ordinal"
        ),
        sa.UniqueConstraint(
            "tenant_id", "id", "preview_id", "bc_id", name="uq_submission_scope"
        ),
        sa.UniqueConstraint("tenant_id", "id", name="uq_submission_tenant"),
        sa.UniqueConstraint("tenant_id", "preview_id", name="uq_submission_preview"),
    )
    op.create_index(
        "ix_submission_page",
        "build_submission",
        ["tenant_id", "bc_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_submission_repair",
        "build_submission",
        ["expanded", "repair_after", "id"],
        unique=False,
    )
    op.create_table(
        "submission_request",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "submission_id", "preview_id", "bc_id"],
            [
                "build_submission.tenant_id",
                "build_submission.id",
                "build_submission.preview_id",
                "build_submission.bc_id",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "request_id"),
    )
    op.create_table(
        "draft_unit_reservation",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("drama_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "draft_id", "bc_id"],
            ["build_draft.tenant_id", "build_draft.id", "build_draft.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "submission_id", "preview_id", "bc_id"],
            [
                "build_submission.tenant_id",
                "build_submission.id",
                "build_submission.preview_id",
                "build_submission.bc_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "unit_id", "preview_id", "bc_id"],
            [
                "build_unit.tenant_id",
                "build_unit.id",
                "build_unit.preview_id",
                "build_unit.bc_id",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "draft_id", "drama_id", "advertiser_id"),
    )
    op.create_index(
        "ix_reservation_submission",
        "draft_unit_reservation",
        ["tenant_id", "submission_id", "unit_id"],
        unique=False,
    )
    op.create_table(
        "submission_unit",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("disposition", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expanded", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "disposition IN ('INCLUDED','EXCLUDED')",
            name="ck_submission_unit_disposition",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "submission_id", "preview_id", "bc_id"],
            [
                "build_submission.tenant_id",
                "build_submission.id",
                "build_submission.preview_id",
                "build_submission.bc_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "unit_id", "preview_id", "bc_id"],
            [
                "build_unit.tenant_id",
                "build_unit.id",
                "build_unit.preview_id",
                "build_unit.bc_id",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "submission_id", "unit_id"),
        sa.UniqueConstraint(
            "tenant_id",
            "submission_id",
            "preview_id",
            "bc_id",
            "unit_id",
            name="uq_submission_unit_scope",
        ),
    )
    op.create_table(
        "execution_step",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "step_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("planned_ad_id", sa.Uuid(), nullable=True),
        sa.Column("material_id", sa.Uuid(), nullable=True),
        sa.Column("parent_step_id", sa.Uuid(), nullable=True),
        sa.Column("distribution_id", sa.Uuid(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phase", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("remote_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "request_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "request_body_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column("resolved", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "operation_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("review_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mismatch", sa.Boolean(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dispatch_revision", sa.Integer(), nullable=False),
        sa.Column("dispatch_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('MATERIAL','CTA','CAMPAIGN','ADGROUP','AD','READBACK')",
            name="ck_step_kind",
        ),
        sa.CheckConstraint(
            "phase != 'REQUEST_ARMED' OR (request_body IS NOT NULL AND request_body_digest IS NOT NULL)",
            name="ck_step_request_intent",
        ),
        sa.CheckConstraint(
            "phase IN ('IDLE','CLAIMED','REQUEST_ARMED','DONE')", name="ck_step_phase"
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED','PENDING','RUNNING','SUCCEEDED','FAILED','RETRYABLE','UNKNOWN')",
            name="ck_step_status",
        ),
        sa.CheckConstraint(
            "(lease_token IS NULL) = (lease_expires_at IS NULL)", name="ck_step_lease"
        ),
        sa.CheckConstraint(
            "attempt >= 0 AND dispatch_revision >= 0", name="ck_step_counters"
        ),
        sa.CheckConstraint(
            "remote_id IS NULL OR length(trim(remote_id)) > 0", name="ck_step_remote_id"
        ),
        sa.ForeignKeyConstraint(
            ["dispatch_id"],
            ["pending_dispatch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["distribution_id"],
            ["material_distribution.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "material_id"],
            ["material_file.tenant_id", "material_file.bc_id", "material_file.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "group_id"],
            ["planned_group.tenant_id", "planned_group.preview_id", "planned_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "planned_ad_id"],
            ["planned_ad.tenant_id", "planned_ad.preview_id", "planned_ad.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "submission_id", "parent_step_id"],
            [
                "execution_step.tenant_id",
                "execution_step.submission_id",
                "execution_step.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "submission_id", "preview_id", "bc_id", "unit_id"],
            [
                "submission_unit.tenant_id",
                "submission_unit.submission_id",
                "submission_unit.preview_id",
                "submission_unit.bc_id",
                "submission_unit.unit_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "submission_id", "preview_id", "bc_id"],
            [
                "build_submission.tenant_id",
                "build_submission.id",
                "build_submission.preview_id",
                "build_submission.bc_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "submission_id", "id", name="uq_step_scope"),
        sa.UniqueConstraint(
            "tenant_id", "submission_id", "step_key", name="uq_execution_step_key"
        ),
    )
    op.create_index(
        "ix_execution_step_due",
        "execution_step",
        ["status", "due_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_execution_step_unit",
        "execution_step",
        ["tenant_id", "submission_id", "unit_id", "kind", "id"],
        unique=False,
    )
    op.create_table(
        "step_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "conclusion", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempt >= 0", name="ck_evidence_attempt"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "submission_id", "step_id"],
            [
                "execution_step.tenant_id",
                "execution_step.submission_id",
                "execution_step.id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_step_evidence_page",
        "step_evidence",
        ["tenant_id", "submission_id", "observed_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute("""
    CREATE FUNCTION build_execution_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN RAISE EXCEPTION 'immutable execution history' USING ERRCODE='23514'; END $$;
    CREATE TRIGGER step_evidence_immutable BEFORE UPDATE OR DELETE ON step_evidence
      FOR EACH ROW EXECUTE FUNCTION build_execution_immutable();
    CREATE TRIGGER submission_request_immutable BEFORE UPDATE OR DELETE ON submission_request
      FOR EACH ROW EXECUTE FUNCTION build_execution_immutable();
    CREATE TRIGGER draft_unit_reservation_immutable BEFORE UPDATE OR DELETE ON draft_unit_reservation
      FOR EACH ROW EXECUTE FUNCTION build_execution_immutable();

    CREATE FUNCTION build_execution_scope() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE u build_unit; s build_submission; p execution_step;
    BEGIN
      IF TG_TABLE_NAME='build_submission' THEN
        IF TG_OP='UPDATE' AND (NEW.tenant_id,NEW.bc_id,NEW.preview_id,NEW.draft_id,NEW.actor_id,NEW.ordinal)
          IS DISTINCT FROM (OLD.tenant_id,OLD.bc_id,OLD.preview_id,OLD.draft_id,OLD.actor_id,OLD.ordinal) THEN
          RAISE EXCEPTION 'immutable submission intent' USING ERRCODE='23514';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM build_preview WHERE tenant_id=NEW.tenant_id AND id=NEW.preview_id AND draft_id=NEW.draft_id AND bc_id=NEW.bc_id AND content_digest IS NOT NULL) THEN
          RAISE EXCEPTION 'submission preview mismatch' USING ERRCODE='23503';
        END IF;
        RETURN NEW;
      END IF;
      SELECT * INTO u FROM build_unit WHERE tenant_id=NEW.tenant_id AND id=NEW.unit_id AND preview_id=NEW.preview_id AND bc_id=NEW.bc_id;
      SELECT * INTO s FROM build_submission WHERE tenant_id=NEW.tenant_id AND id=NEW.submission_id AND preview_id=NEW.preview_id AND bc_id=NEW.bc_id;
      IF u.id IS NULL OR s.id IS NULL THEN RAISE EXCEPTION 'execution scope mismatch' USING ERRCODE='23503'; END IF;
      IF TG_TABLE_NAME='draft_unit_reservation' THEN
        IF (NEW.draft_id,NEW.drama_id,NEW.advertiser_id) IS DISTINCT FROM (s.draft_id,u.drama_id,u.advertiser_id) THEN
          RAISE EXCEPTION 'reservation scope mismatch' USING ERRCODE='23503';
        END IF;
      ELSIF TG_TABLE_NAME='execution_step' THEN
        IF TG_OP='UPDATE' AND (NEW.tenant_id,NEW.submission_id,NEW.preview_id,NEW.bc_id,NEW.unit_id,NEW.kind,NEW.step_key,NEW.group_id,NEW.planned_ad_id,NEW.material_id,NEW.parent_step_id)
          IS DISTINCT FROM (OLD.tenant_id,OLD.submission_id,OLD.preview_id,OLD.bc_id,OLD.unit_id,OLD.kind,OLD.step_key,OLD.group_id,OLD.planned_ad_id,OLD.material_id,OLD.parent_step_id) THEN
          RAISE EXCEPTION 'immutable step intent' USING ERRCODE='23514';
        END IF;
        IF TG_OP='UPDATE' AND OLD.request_body IS NOT NULL AND (NEW.request_body,NEW.request_body_digest) IS DISTINCT FROM (OLD.request_body,OLD.request_body_digest) THEN
          RAISE EXCEPTION 'immutable armed request' USING ERRCODE='23514';
        END IF;
        IF NEW.group_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM planned_group WHERE tenant_id=NEW.tenant_id AND preview_id=NEW.preview_id AND id=NEW.group_id AND unit_id=NEW.unit_id) THEN
          RAISE EXCEPTION 'group unit mismatch' USING ERRCODE='23503';
        END IF;
        IF NEW.planned_ad_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM planned_ad WHERE tenant_id=NEW.tenant_id AND preview_id=NEW.preview_id AND id=NEW.planned_ad_id AND group_id=NEW.group_id) THEN
          RAISE EXCEPTION 'ad group mismatch' USING ERRCODE='23503';
        END IF;
        IF NEW.material_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM preview_group_material WHERE tenant_id=NEW.tenant_id AND preview_id=NEW.preview_id AND drama_id=u.drama_id AND material_id=NEW.material_id) THEN
          RAISE EXCEPTION 'material snapshot mismatch' USING ERRCODE='23503';
        END IF;
        IF NEW.distribution_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM material_distribution WHERE id=NEW.distribution_id AND tenant_id=NEW.tenant_id AND bc_id=NEW.bc_id AND material_id=NEW.material_id AND advertiser_id=u.advertiser_id) THEN
          RAISE EXCEPTION 'distribution target mismatch' USING ERRCODE='23503';
        END IF;
        IF NEW.parent_step_id IS NOT NULL THEN
          SELECT * INTO p FROM execution_step WHERE tenant_id=NEW.tenant_id AND submission_id=NEW.submission_id AND id=NEW.parent_step_id AND unit_id=NEW.unit_id;
          IF p.id IS NULL THEN RAISE EXCEPTION 'step parent mismatch' USING ERRCODE='23503'; END IF;
        END IF;
      END IF;
      RETURN NEW;
    END $$;
    CREATE TRIGGER submission_scope BEFORE INSERT OR UPDATE ON build_submission FOR EACH ROW EXECUTE FUNCTION build_execution_scope();
    CREATE TRIGGER reservation_scope BEFORE INSERT ON draft_unit_reservation FOR EACH ROW EXECUTE FUNCTION build_execution_scope();
    CREATE TRIGGER execution_step_scope BEFORE INSERT OR UPDATE ON execution_step FOR EACH ROW EXECUTE FUNCTION build_execution_scope();
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_step_evidence_page", table_name="step_evidence")
    op.drop_table("step_evidence")
    op.drop_index("ix_execution_step_unit", table_name="execution_step")
    op.drop_index("ix_execution_step_due", table_name="execution_step")
    op.drop_table("execution_step")
    op.drop_table("submission_unit")
    op.drop_index("ix_reservation_submission", table_name="draft_unit_reservation")
    op.drop_table("draft_unit_reservation")
    op.drop_table("submission_request")
    op.drop_index("ix_submission_repair", table_name="build_submission")
    op.drop_index("ix_submission_page", table_name="build_submission")
    op.drop_table("build_submission")
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION build_execution_scope()")
    op.execute("DROP FUNCTION build_execution_immutable()")
