"""persist bounded submission recovery and immutable receipts

Revision ID: 0010_submission_recovery
Revises: 0009_execution_dispatch_indexes
Create Date: 2026-09-09 08:16:05.997374

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "0010_submission_recovery"
down_revision = "0009_execution_dispatch_indexes"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submission_recovery",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("request_actor_id", sa.Uuid(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("cursor_step_id", sa.Uuid(), nullable=True),
        sa.Column("scanned_count", sa.Integer(), nullable=False),
        sa.Column("scheduled_count", sa.Integer(), nullable=False),
        sa.Column(
            "reason_code", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatch_revision", sa.Integer(), nullable=False),
        sa.Column("dispatch_id", sa.Uuid(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("repair_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('RETRY','RECONCILE')", name="ck_recovery_kind"),
        sa.CheckConstraint(
            "state IN ('QUEUED','RUNNING','COMPLETED','FAILED')",
            name="ck_recovery_state",
        ),
        sa.CheckConstraint(
            "(lease_token IS NULL) = (lease_expires_at IS NULL)",
            name="ck_recovery_lease",
        ),
        sa.CheckConstraint(
            "scheduled_count >= 0 AND scanned_count >= scheduled_count AND dispatch_revision >= 0",
            name="ck_recovery_counts",
        ),
        sa.ForeignKeyConstraint(
            ["dispatch_id"],
            ["pending_dispatch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "submission_id", "preview_id", "bc_id"],
            [
                "build_submission.tenant_id",
                "build_submission.id",
                "build_submission.preview_id",
                "build_submission.bc_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "id",
            "request_id",
            "submission_id",
            "bc_id",
            "kind",
            name="uq_recovery_scope",
        ),
        sa.UniqueConstraint("tenant_id", "request_id", name="uq_recovery_request"),
    )
    op.create_index(
        "ix_recovery_repair",
        "submission_recovery",
        ["state", "repair_after", "id"],
        unique=False,
    )
    op.create_index(
        "ix_recovery_submission",
        "submission_recovery",
        ["tenant_id", "submission_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "submission_recovery_request",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            [
                "tenant_id",
                "recovery_id",
                "request_id",
                "submission_id",
                "bc_id",
                "kind",
            ],
            [
                "submission_recovery.tenant_id",
                "submission_recovery.id",
                "submission_recovery.request_id",
                "submission_recovery.submission_id",
                "submission_recovery.bc_id",
                "submission_recovery.kind",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "request_id"),
    )
    op.execute("""
      CREATE FUNCTION retain_recovery_intent() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN
        IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'recovery intent is permanent'; END IF;
        IF ROW(NEW.id,NEW.tenant_id,NEW.request_id,NEW.submission_id,NEW.preview_id,NEW.bc_id,NEW.kind,NEW.request_actor_id,NEW.created_at)
           IS DISTINCT FROM ROW(OLD.id,OLD.tenant_id,OLD.request_id,OLD.submission_id,OLD.preview_id,OLD.bc_id,OLD.kind,OLD.request_actor_id,OLD.created_at)
        THEN RAISE EXCEPTION 'recovery intent is immutable'; END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER recovery_intent_immutable BEFORE UPDATE OR DELETE ON submission_recovery
      FOR EACH ROW EXECUTE FUNCTION retain_recovery_intent();
      CREATE FUNCTION retain_recovery_receipt() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN RAISE EXCEPTION 'recovery receipt is immutable'; END $$;
      CREATE TRIGGER recovery_receipt_immutable BEFORE UPDATE OR DELETE ON submission_recovery_request
      FOR EACH ROW EXECUTE FUNCTION retain_recovery_receipt();
    """)
    # ### end Alembic commands ###


def downgrade():
    op.execute("DROP TRIGGER recovery_receipt_immutable ON submission_recovery_request")
    op.execute("DROP FUNCTION retain_recovery_receipt()")
    op.execute("DROP TRIGGER recovery_intent_immutable ON submission_recovery")
    op.execute("DROP FUNCTION retain_recovery_intent()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("submission_recovery_request")
    op.drop_index("ix_recovery_submission", table_name="submission_recovery")
    op.drop_index("ix_recovery_repair", table_name="submission_recovery")
    op.drop_table("submission_recovery")
    # ### end Alembic commands ###
