"""account directory

Revision ID: 02c_directory
Revises: 02b_connections
Create Date: 2026-09-09 03:19:10.114428

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '02c_directory'
down_revision = '02b_connections'
branch_labels = None
depends_on = None


def upgrade():
    op.create_unique_constraint('uq_authorization_attempt_tenant_id', 'authorization_attempt', ['tenant_id', 'id'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertiser_account',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('advertiser_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remote_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ownership_conflict', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'advertiser_id')
    )
    op.create_index('ix_advertiser_tenant_name_id', 'advertiser_account', ['tenant_id', 'name', 'advertiser_id'], unique=False)
    op.create_table('external_asset_owner',
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('owner_tenant_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('BC','ADVERTISER')", name='ck_external_asset_kind'),
    sa.ForeignKeyConstraint(['owner_tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('kind', 'external_id')
    )
    op.create_table('tenant_bc',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('bc_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ownership_conflict', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'bc_id')
    )
    op.create_table('discovery_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_attempt_id', sa.Uuid(), nullable=True),
    sa.Column('credential_version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bc_cursor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('claimed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('RUNNING','ADMISSION_WAIT','ERROR','COMPLETE','CANCELLED')", name='ck_discovery_status'),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'candidate_attempt_id'], ['authorization_attempt.tenant_id', 'authorization_attempt.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'connection_id'], ['tiktok_connection.tenant_id', 'tiktok_connection.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_discovery_run_tenant_id')
    )
    op.create_index(op.f('ix_discovery_run_tenant_id'), 'discovery_run', ['tenant_id'], unique=False)
    op.create_index('uq_discovery_active_connection', 'discovery_run', ['tenant_id', 'connection_id'], unique=True, postgresql_where=sa.text("status IN ('RUNNING','ADMISSION_WAIT')"))
    op.create_table('bc_account_access',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('bc_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('advertiser_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('in_bc', sa.Boolean(), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('can_upload', sa.Boolean(), nullable=False),
    sa.Column('can_build', sa.Boolean(), nullable=False),
    sa.Column('permission_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen_run_id', sa.Uuid(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("permission_state IN ('UNKNOWN','VERIFIED','METADATA_INCOMPLETE')", name='ck_access_permission'),
    sa.ForeignKeyConstraint(['tenant_id', 'advertiser_id'], ['advertiser_account.tenant_id', 'advertiser_account.advertiser_id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'bc_id'], ['tenant_bc.tenant_id', 'tenant_bc.bc_id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'connection_id'], ['tiktok_connection.tenant_id', 'tiktok_connection.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'last_seen_run_id'], ['discovery_run.tenant_id', 'discovery_run.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'bc_id', 'advertiser_id', 'connection_id')
    )
    op.create_index('ix_access_tenant_bc_active_id', 'bc_account_access', ['tenant_id', 'bc_id', 'active', 'advertiser_id'], unique=False)
    op.create_table('discovery_seen',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('bc_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('last_page', sa.Boolean(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('page > 0 AND processed_count >= 0', name='ck_discovery_seen_page'),
    sa.ForeignKeyConstraint(['run_id'], ['discovery_run.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'bc_id', 'page')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discovery_seen')
    op.drop_index('ix_access_tenant_bc_active_id', table_name='bc_account_access')
    op.drop_table('bc_account_access')
    op.drop_index('uq_discovery_active_connection', table_name='discovery_run', postgresql_where=sa.text("status IN ('RUNNING','ADMISSION_WAIT')"))
    op.drop_index(op.f('ix_discovery_run_tenant_id'), table_name='discovery_run')
    op.drop_table('discovery_run')
    op.drop_constraint('uq_authorization_attempt_tenant_id', 'authorization_attempt', type_='unique')
    op.drop_table('tenant_bc')
    op.drop_table('external_asset_owner')
    op.drop_index('ix_advertiser_tenant_name_id', table_name='advertiser_account')
    op.drop_table('advertiser_account')
    # ### end Alembic commands ###
