"""ads reporting data

Revision ID: ads_reporting_data
Revises: material_push
Create Date: 2026-09-30 16:05:37.713852

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ads_reporting_data"
down_revision = "material_push"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_balance_observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(), nullable=True),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column(
            "availability", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "balance_scope", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column(
            "scope_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_connection_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source_channel", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.CheckConstraint(
            "amount IS NULL OR amount NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric)",
            name="ck_balance_finite",
        ),
        sa.CheckConstraint(
            "balance_scope IN ('ADVERTISER','PORTFOLIO','UNKNOWN')",
            name="ck_balance_scope",
        ),
        sa.CheckConstraint(
            "(source_connection_id IS NULL) = (source_channel IS NULL)",
            name="ck_balance_source",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_connection_id", "source_channel"],
            [
                "tiktok_connection.tenant_id",
                "tiktok_connection.id",
                "tiktok_connection.kind",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_account_balance_history",
        "account_balance_observation",
        ["tenant_id", "advertiser_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "ad_directory_run",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "frozen_route", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "partition_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("claim_generation", sa.Integer(), nullable=False),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("claimed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_page", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "coverage", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("missing_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "request_sequence",
            sa.BigInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column(
            "ad_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.CheckConstraint(
            "frozen_route ? 'binding_revision' AND frozen_route->>'channel' = channel",
            name="ck_ad_directory_run_route_generation",
        ),
        sa.CheckConstraint(
            "frozen_route IS NULL OR COALESCE((jsonb_typeof(frozen_route) = 'object' AND frozen_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND frozen_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] - 'binding_revision' = '{}'::jsonb AND (NOT frozen_route ? 'binding_revision' OR (jsonb_typeof(frozen_route->'binding_revision') = 'number' AND frozen_route->>'binding_revision' ~ '^[0-9]+$')) AND jsonb_typeof(frozen_route->'tenant_id') = 'string' AND jsonb_typeof(frozen_route->'bc_id') = 'string' AND jsonb_typeof(frozen_route->'connection_id') = 'string' AND jsonb_typeof(frozen_route->'channel') = 'string' AND jsonb_typeof(frozen_route->'authorization_revision') = 'number' AND jsonb_typeof(frozen_route->'adapter_contract_revision') = 'string' AND frozen_route->>'tenant_id' = tenant_id::text AND frozen_route->>'bc_id' = bc_id AND length(btrim(frozen_route->>'bc_id')) > 0 AND frozen_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND frozen_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP') AND frozen_route->>'authorization_revision' ~ '^[0-9]+$' AND length(btrim(frozen_route->>'adapter_contract_revision')) > 0 AND frozen_route->>'connection_id' = connection_id::text), false)",
            name="ck_ad_directory_run_frozen_route",
        ),
        sa.CheckConstraint(
            "kind IN ('campaign','adgroup','ad','creative')",
            name="ck_ad_directory_run_kind",
        ),
        sa.CheckConstraint(
            "partition_key ~ '^[0-9a-f]{64}$'", name="ck_ad_directory_run_partition"
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED','RUNNING','ADMISSION_WAIT','WAITING_REMOTE','COMPLETE','FAILED','CANCELLED','STALE')",
            name="ck_ad_directory_run_status",
        ),
        sa.CheckConstraint(
            "claim_generation >= 0 AND next_page > 0 AND (published_version IS NULL OR published_version > 0)",
            name="ck_ad_directory_run_numbers",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "actor_id"],
            ["tenant_membership.tenant_id", "tenant_membership.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id"],
            ["tenant_bc.tenant_id", "tenant_bc.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id", "channel"],
            [
                "tiktok_connection.tenant_id",
                "tiktok_connection.id",
                "tiktok_connection.kind",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_sequence"),
        sa.UniqueConstraint(
            "tenant_id", "advertiser_id", "id", name="uq_ad_directory_run_scope"
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "request_id",
            "advertiser_id",
            "partition_key",
            name="uq_ad_directory_run_request",
        ),
    )
    op.create_index(
        "ix_ad_directory_run_due",
        "ad_directory_run",
        ["status", "next_attempt_at", "claimed_until"],
        unique=False,
    )
    op.create_index(
        "ix_ad_directory_run_partition",
        "ad_directory_run",
        ["tenant_id", "advertiser_id", "partition_key", "request_sequence"],
        unique=False,
    )
    op.create_table(
        "ad_object",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column(
            "remote_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "parent_kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True
        ),
        sa.Column(
            "parent_remote_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column(
            "ad_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "operation_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("review_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("delivery_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_version", sa.Integer(), nullable=False),
        sa.Column("source_connection_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source_channel", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.CheckConstraint(
            "(parent_kind IS NULL) = (parent_remote_id IS NULL) AND (parent_kind IS NULL OR parent_kind IN ('campaign','adgroup','ad','creative'))",
            name="ck_ad_object_parent",
        ),
        sa.CheckConstraint(
            "kind IN ('campaign','adgroup','ad','creative')", name="ck_ad_object_kind"
        ),
        sa.CheckConstraint(
            "(source_connection_id IS NULL) = (source_channel IS NULL)",
            name="ck_ad_object_source",
        ),
        sa.CheckConstraint("published_version > 0", name="ck_ad_object_version"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_connection_id", "source_channel"],
            [
                "tiktok_connection.tenant_id",
                "tiktok_connection.id",
                "tiktok_connection.kind",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "advertiser_id", "kind", "remote_id"),
    )
    op.create_index(
        "ix_ad_object_parent",
        "ad_object",
        ["tenant_id", "advertiser_id", "parent_kind", "parent_remote_id", "kind"],
        unique=False,
    )
    op.create_table(
        "campaign_name_projection",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "campaign_remote_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("name_revision", sa.Integer(), nullable=False),
        sa.Column("raw_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("drama_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("parser_revision", sa.Integer(), nullable=False),
        sa.Column("grouping_revision", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'VALID' AND provider_label IS NOT NULL AND drama_name IS NOT NULL) OR (status = 'INVALID' AND provider_label IS NULL AND drama_name IS NULL)",
            name="ck_campaign_name_status",
        ),
        sa.CheckConstraint(
            "parser_revision > 0 AND name_revision > 0 AND grouping_revision > 0 AND grouping_revision <= name_revision",
            name="ck_campaign_name_revisions",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "advertiser_id", "campaign_remote_id", "name_revision"
        ),
    )
    op.create_index(
        "ix_campaign_name_group",
        "campaign_name_projection",
        [
            "tenant_id",
            "provider_label",
            "drama_name",
            "advertiser_id",
            "campaign_remote_id",
        ],
        unique=False,
    )
    op.create_table(
        "report_observation",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bucket_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "granularity", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "report_contract",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "metric_family", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column(
            "timezone", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "attribution", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "subject_kind", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column(
            "subject_key", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "availability", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "membership_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("name_revision", sa.Integer(), nullable=False),
        sa.Column("grouping_revision", sa.Integer(), nullable=False),
        sa.Column("published_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "subject_kind IN ('account','campaign')", name="ck_report_observation_kind"
        ),
        sa.CheckConstraint(
            "bucket_start < bucket_end AND name_revision >= 0 AND grouping_revision >= 0 AND published_version > 0",
            name="ck_report_observation_versions",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_report_observation_history",
        "report_observation",
        ["tenant_id", "advertiser_id", "subject_kind", "observed_at"],
        unique=False,
    )
    op.create_table(
        "report_sync_run",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "frozen_route", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "partition_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("claim_generation", sa.Integer(), nullable=False),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("claimed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_page", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "coverage", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("missing_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "request_sequence",
            sa.BigInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column(
            "task_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column(
            "task_status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
        sa.CheckConstraint(
            "frozen_route ? 'binding_revision' AND frozen_route->>'channel' = channel",
            name="ck_report_sync_run_route_generation",
        ),
        sa.CheckConstraint(
            "frozen_route IS NULL OR COALESCE((jsonb_typeof(frozen_route) = 'object' AND frozen_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND frozen_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] - 'binding_revision' = '{}'::jsonb AND (NOT frozen_route ? 'binding_revision' OR (jsonb_typeof(frozen_route->'binding_revision') = 'number' AND frozen_route->>'binding_revision' ~ '^[0-9]+$')) AND jsonb_typeof(frozen_route->'tenant_id') = 'string' AND jsonb_typeof(frozen_route->'bc_id') = 'string' AND jsonb_typeof(frozen_route->'connection_id') = 'string' AND jsonb_typeof(frozen_route->'channel') = 'string' AND jsonb_typeof(frozen_route->'authorization_revision') = 'number' AND jsonb_typeof(frozen_route->'adapter_contract_revision') = 'string' AND frozen_route->>'tenant_id' = tenant_id::text AND frozen_route->>'bc_id' = bc_id AND length(btrim(frozen_route->>'bc_id')) > 0 AND frozen_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND frozen_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP') AND frozen_route->>'authorization_revision' ~ '^[0-9]+$' AND length(btrim(frozen_route->>'adapter_contract_revision')) > 0 AND frozen_route->>'connection_id' = connection_id::text), false)",
            name="ck_report_sync_run_frozen_route",
        ),
        sa.CheckConstraint(
            "partition_key ~ '^[0-9a-f]{64}$'", name="ck_report_sync_run_partition"
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED','RUNNING','ADMISSION_WAIT','WAITING_REMOTE','COMPLETE','FAILED','CANCELLED','STALE')",
            name="ck_report_sync_run_status",
        ),
        sa.CheckConstraint(
            "claim_generation >= 0 AND next_page > 0 AND (published_version IS NULL OR published_version > 0)",
            name="ck_report_sync_run_numbers",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "actor_id"],
            ["tenant_membership.tenant_id", "tenant_membership.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id"],
            ["tenant_bc.tenant_id", "tenant_bc.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id", "channel"],
            [
                "tiktok_connection.tenant_id",
                "tiktok_connection.id",
                "tiktok_connection.kind",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_sequence"),
        sa.UniqueConstraint(
            "tenant_id", "advertiser_id", "id", name="uq_report_sync_run_scope"
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "request_id",
            "advertiser_id",
            "partition_key",
            name="uq_report_sync_run_request",
        ),
    )
    op.create_index(
        "ix_report_sync_run_due",
        "report_sync_run",
        ["status", "next_attempt_at", "claimed_until"],
        unique=False,
    )
    op.create_index(
        "ix_report_sync_run_partition",
        "report_sync_run",
        ["tenant_id", "advertiser_id", "partition_key", "request_sequence"],
        unique=False,
    )
    op.create_table(
        "sync_schedule",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "frozen_route", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "schedule_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "requested_coverage",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "completed_coverage",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("last_request_id", sa.Uuid(), nullable=True),
        sa.Column("claim_generation", sa.Integer(), nullable=False),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("claimed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.CheckConstraint(
            "frozen_route ? 'binding_revision' AND frozen_route->>'channel' = channel",
            name="ck_sync_schedule_route_generation",
        ),
        sa.CheckConstraint(
            "frozen_route IS NULL OR COALESCE((jsonb_typeof(frozen_route) = 'object' AND frozen_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND frozen_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] - 'binding_revision' = '{}'::jsonb AND (NOT frozen_route ? 'binding_revision' OR (jsonb_typeof(frozen_route->'binding_revision') = 'number' AND frozen_route->>'binding_revision' ~ '^[0-9]+$')) AND jsonb_typeof(frozen_route->'tenant_id') = 'string' AND jsonb_typeof(frozen_route->'bc_id') = 'string' AND jsonb_typeof(frozen_route->'connection_id') = 'string' AND jsonb_typeof(frozen_route->'channel') = 'string' AND jsonb_typeof(frozen_route->'authorization_revision') = 'number' AND jsonb_typeof(frozen_route->'adapter_contract_revision') = 'string' AND frozen_route->>'tenant_id' = tenant_id::text AND frozen_route->>'bc_id' = bc_id AND length(btrim(frozen_route->>'bc_id')) > 0 AND frozen_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND frozen_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP') AND frozen_route->>'authorization_revision' ~ '^[0-9]+$' AND length(btrim(frozen_route->>'adapter_contract_revision')) > 0 AND frozen_route->>'connection_id' = connection_id::text), false)",
            name="ck_sync_schedule_frozen_route",
        ),
        sa.CheckConstraint(
            "scope IN ('directory','active','report','balance','history','targeted')",
            name="ck_sync_schedule_scope",
        ),
        sa.CheckConstraint(
            "(start_date IS NULL AND end_date IS NULL) OR (start_date IS NOT NULL AND end_date IS NOT NULL AND start_date <= end_date)",
            name="ck_sync_schedule_dates",
        ),
        sa.CheckConstraint(
            "claim_generation >= 0 AND interval_seconds > 0",
            name="ck_sync_schedule_numbers",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "actor_id"],
            ["tenant_membership.tenant_id", "tenant_membership.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id"],
            ["tenant_bc.tenant_id", "tenant_bc.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id", "channel"],
            [
                "tiktok_connection.tenant_id",
                "tiktok_connection.id",
                "tiktok_connection.kind",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "bc_id",
            "advertiser_id",
            "scope",
            "schedule_key",
            name="uq_sync_schedule_scope",
        ),
    )
    op.create_index(
        "ix_sync_schedule_due",
        "sync_schedule",
        ["enabled", "next_due_at", "claimed_until"],
        unique=False,
    )
    op.create_table(
        "ad_directory_page",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("claim_generation", sa.Integer(), nullable=False),
        sa.Column("next_page", sa.Integer(), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "coverage", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("missing_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_version", sa.Integer(), nullable=True),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("materials", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "page > 0 AND claim_generation > 0 AND (next_page IS NULL OR next_page > page) AND (NOT complete OR next_page IS NULL)",
            name="ck_ad_directory_page_numbers",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id", "run_id"],
            [
                "ad_directory_run.tenant_id",
                "ad_directory_run.advertiser_id",
                "ad_directory_run.id",
            ],
        ),
        sa.PrimaryKeyConstraint("run_id", "page"),
    )
    op.create_index(
        "ix_ad_directory_page_scope",
        "ad_directory_page",
        ["tenant_id", "advertiser_id", "run_id"],
        unique=False,
    )
    op.create_table(
        "ad_material_reference",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "ad_remote_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "platform_material_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "ad_material_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column(
            "material_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "main_material_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column(
            "main_material_type",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=True,
        ),
        sa.Column(
            "creative_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("local_material_id", sa.Uuid(), nullable=True),
        sa.Column(
            "operation_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("published_version", sa.Integer(), nullable=False),
        sa.CheckConstraint("published_version > 0", name="ck_ad_material_version"),
        sa.CheckConstraint(
            "(main_material_id IS NULL) = (main_material_type IS NULL)",
            name="ck_ad_material_main_identity",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(creative_ids) = 'array'", name="ck_ad_material_creatives"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "local_material_id"],
            ["material_file.tenant_id", "material_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "advertiser_id",
            "ad_remote_id",
            "platform_material_id",
            "ad_material_id",
            "material_type",
            name="uq_ad_material_usage",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_ad_material_ad",
        "ad_material_reference",
        ["tenant_id", "advertiser_id", "ad_remote_id"],
        unique=False,
    )
    op.create_table(
        "report_coverage",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bucket_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "granularity", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "report_contract",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "metric_family", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column(
            "timezone", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "attribution", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "partition_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "filter_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "requested_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("missing_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_version", sa.Integer(), nullable=False),
        sa.Column("request_sequence", sa.BigInteger(), nullable=False),
        sa.Column("source_run_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "bucket_start < bucket_end AND published_version > 0 AND request_sequence > 0",
            name="ck_report_coverage_versions",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id", "source_run_id"],
            [
                "report_sync_run.tenant_id",
                "report_sync_run.advertiser_id",
                "report_sync_run.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "advertiser_id",
            "partition_key",
            "bucket_start",
            "bucket_end",
            name="uq_report_coverage_partition",
        ),
    )
    op.create_index(
        "ix_report_coverage_period",
        "report_coverage",
        ["tenant_id", "advertiser_id", "report_contract", "bucket_start"],
        unique=False,
    )
    op.create_table(
        "report_fact",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bucket_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "granularity", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "report_contract",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column(
            "metric_family", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column(
            "timezone", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "attribution", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "subject_key", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "metric_name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.CheckConstraint(
            "jsonb_typeof(attributes) = 'object'", name="ck_report_fact_attributes"
        ),
        sa.Column("value", sa.Numeric(), nullable=True),
        sa.Column(
            "availability", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("published_version", sa.Integer(), nullable=False),
        sa.Column("request_sequence", sa.BigInteger(), nullable=False),
        sa.Column(
            "source_partition_key",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("source_run_id", sa.Uuid(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(subject_key) = 'array' AND jsonb_array_length(subject_key) > 0",
            name="ck_report_fact_subject",
        ),
        sa.CheckConstraint(
            "value IS NULL OR value NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric)",
            name="ck_report_fact_finite",
        ),
        sa.CheckConstraint(
            "bucket_start < bucket_end AND published_version > 0 AND request_sequence > 0",
            name="ck_report_fact_versions",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id", "source_run_id"],
            [
                "report_sync_run.tenant_id",
                "report_sync_run.advertiser_id",
                "report_sync_run.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id"],
            ["advertiser_account.tenant_id", "advertiser_account.advertiser_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "advertiser_id",
            "subject_key",
            "bucket_start",
            "bucket_end",
            "granularity",
            "report_contract",
            "metric_family",
            "currency",
            "timezone",
            "attribution",
            "metric_name",
            name="uq_report_fact_identity",
        ),
    )
    op.create_index(
        "ix_report_fact_period",
        "report_fact",
        [
            "tenant_id",
            "advertiser_id",
            "report_contract",
            "metric_family",
            "bucket_start",
        ],
        unique=False,
    )
    op.create_table(
        "report_staged_page",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("claim_generation", sa.Integer(), nullable=False),
        sa.Column("next_page", sa.Integer(), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "coverage", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("missing_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_version", sa.Integer(), nullable=True),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "task_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.CheckConstraint(
            "page > 0 AND claim_generation > 0 AND (next_page IS NULL OR next_page > page) AND (NOT complete OR next_page IS NULL)",
            name="ck_report_staged_page_numbers",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "advertiser_id", "run_id"],
            [
                "report_sync_run.tenant_id",
                "report_sync_run.advertiser_id",
                "report_sync_run.id",
            ],
        ),
        sa.PrimaryKeyConstraint("run_id", "page"),
    )
    op.create_index(
        "ix_report_staged_page_scope",
        "report_staged_page",
        ["tenant_id", "advertiser_id", "run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # 仅空表允许撤回；不静默删除已采集的投放事实或审计记录。
    tables = (
        "account_balance_observation",
        "ad_directory_run",
        "ad_object",
        "campaign_name_projection",
        "report_observation",
        "report_sync_run",
        "sync_schedule",
        "ad_directory_page",
        "ad_material_reference",
        "report_coverage",
        "report_fact",
        "report_staged_page",
    )
    for table in tables:
        if op.get_bind().execute(sa.text(f'SELECT 1 FROM "{table}" LIMIT 1')).first():
            raise RuntimeError("已有投放数据，禁止丢弃采集事实或审计记录的降级")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_report_staged_page_scope", table_name="report_staged_page")
    op.drop_table("report_staged_page")
    op.drop_index("ix_report_fact_period", table_name="report_fact")
    op.drop_table("report_fact")
    op.drop_index("ix_report_coverage_period", table_name="report_coverage")
    op.drop_table("report_coverage")
    op.drop_index("ix_ad_material_ad", table_name="ad_material_reference")
    op.drop_table("ad_material_reference")
    op.drop_index("ix_ad_directory_page_scope", table_name="ad_directory_page")
    op.drop_table("ad_directory_page")
    op.drop_index("ix_sync_schedule_due", table_name="sync_schedule")
    op.drop_table("sync_schedule")
    op.drop_index("ix_report_sync_run_partition", table_name="report_sync_run")
    op.drop_index("ix_report_sync_run_due", table_name="report_sync_run")
    op.drop_table("report_sync_run")
    op.drop_index("ix_report_observation_history", table_name="report_observation")
    op.drop_table("report_observation")
    op.drop_index("ix_campaign_name_group", table_name="campaign_name_projection")
    op.drop_table("campaign_name_projection")
    op.drop_index("ix_ad_object_parent", table_name="ad_object")
    op.drop_table("ad_object")
    op.drop_index("ix_ad_directory_run_partition", table_name="ad_directory_run")
    op.drop_index("ix_ad_directory_run_due", table_name="ad_directory_run")
    op.drop_table("ad_directory_run")
    op.drop_index(
        "ix_account_balance_history", table_name="account_balance_observation"
    )
    op.drop_table("account_balance_observation")
    # ### end Alembic commands ###
