"""TikTok channel connections

Revision ID: mcp01
Revises: 0017_preview_naming
Create Date: 2026-09-11 22:59:40.195663

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "mcp01"
down_revision = "0017_preview_naming"
branch_labels = None
depends_on = None


def upgrade():
    # 物理改名承接原值；历史 JSON 请求、远端 ID 和版权方版本完全不改写。
    for table, old, new in (
        ("tiktok_connection", "credential_version", "credential_revision"),
        (
            "authorization_attempt",
            "base_credential_version",
            "base_credential_revision",
        ),
        ("discovery_run", "credential_version", "credential_revision"),
        ("account_capability_job", "credential_version", "credential_revision"),
        ("build_scene_job", "credential_version", "credential_revision"),
    ):
        op.alter_column(
            table,
            old,
            new_column_name=new,
            existing_type=sa.Integer(),
            existing_nullable=False,
        )
    op.add_column(
        "tiktok_connection",
        sa.Column("kind", sa.String(32), nullable=False, server_default="OFFICIAL_API"),
    )
    op.add_column(
        "tiktok_connection",
        sa.Column("display_name", sa.String(255), nullable=False, server_default=""),
    )
    op.add_column(
        "tiktok_connection", sa.Column("service_profile", sa.String(128), nullable=True)
    )
    op.add_column(
        "tiktok_connection",
        sa.Column(
            "authorization_revision", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "tiktok_connection",
        sa.Column(
            "adapter_contract_revision",
            sa.String(128),
            nullable=False,
            server_default="official-api-v1",
        ),
    )
    op.create_unique_constraint(
        "uq_tiktok_connection_tenant_kind",
        "tiktok_connection",
        ["tenant_id", "id", "kind"],
    )
    op.create_check_constraint(
        "ck_tiktok_connection_kind",
        "tiktok_connection",
        "kind IN ('OFFICIAL_API','OFFICIAL_MCP')",
    )
    op.create_check_constraint(
        "ck_tiktok_connection_authorization_revision",
        "tiktok_connection",
        "authorization_revision >= 0",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_authorization_attempt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("base_credential_revision", sa.Integer(), nullable=False),
        sa.Column("base_authorization_revision", sa.Integer(), nullable=False),
        sa.Column(
            "issuer", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False
        ),
        sa.Column(
            "resource", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False
        ),
        sa.Column(
            "redirect_uri",
            sqlmodel.sql.sqltypes.AutoString(length=2048),
            nullable=False,
        ),
        sa.Column(
            "state_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "pkce_verifier_ciphertext",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "candidate_ciphertext", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("claimed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "error_code", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','CLAIMED','CANDIDATE_READY','RESULT_UNKNOWN','CANCELLED','FAILED','ACCEPTED')",
            name="ck_mcp_authorization_attempt_status",
        ),
        sa.CheckConstraint(
            "(claim_id IS NULL) = (claimed_until IS NULL)",
            name="ck_mcp_authorization_attempt_claim",
        ),
        sa.CheckConstraint(
            "base_credential_revision >= 0 AND base_authorization_revision >= 0",
            name="ck_mcp_authorization_attempt_revisions",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "actor_id"],
            ["tenant_membership.tenant_id", "tenant_membership.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id"],
            ["tiktok_connection.tenant_id", "tiktok_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash"),
        sa.UniqueConstraint(
            "tenant_id",
            "connection_id",
            "id",
            name="uq_mcp_authorization_attempt_scope",
        ),
    )
    op.create_index(
        op.f("ix_mcp_authorization_attempt_tenant_id"),
        "mcp_authorization_attempt",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "connection_authorization",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_revision", sa.Integer(), nullable=False),
        sa.Column(
            "upstream_subject",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=True,
        ),
        sa.Column(
            "upstream_grant_id",
            sqlmodel.sql.sqltypes.AutoString(length=512),
            nullable=True,
        ),
        sa.Column(
            "issuer", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True
        ),
        sa.Column(
            "resource", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True
        ),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "permission_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_authorization_id", sa.Uuid(), nullable=True),
        sa.Column("mcp_authorization_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(scopes) = 'array' AND jsonb_typeof(permission_summary) = 'object'",
            name="ck_connection_authorization_facts",
        ),
        sa.CheckConstraint(
            "authorization_revision >= 0", name="ck_connection_authorization_revision"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id", "mcp_authorization_attempt_id"],
            [
                "mcp_authorization_attempt.tenant_id",
                "mcp_authorization_attempt.connection_id",
                "mcp_authorization_attempt.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id", "previous_authorization_id"],
            [
                "connection_authorization.tenant_id",
                "connection_authorization.connection_id",
                "connection_authorization.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id"],
            ["tiktok_connection.tenant_id", "tiktok_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "connection_id",
            "authorization_revision",
            name="uq_connection_authorization_revision",
        ),
        sa.UniqueConstraint(
            "tenant_id", "connection_id", "id", name="uq_connection_authorization_scope"
        ),
    )
    op.create_index(
        op.f("ix_connection_authorization_tenant_id"),
        "connection_authorization",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "connection_tool_observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_attempt_id", sa.Uuid(), nullable=True),
        sa.Column(
            "schema_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column(
            "expected_contract_revision",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("pagination_complete", sa.Boolean(), nullable=False),
        sa.Column(
            "tool_schemas", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "call_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(tool_schemas) = 'object' AND jsonb_typeof(call_evidence) = 'object'",
            name="ck_connection_tool_observation_evidence",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id", "candidate_attempt_id"],
            [
                "mcp_authorization_attempt.tenant_id",
                "mcp_authorization_attempt.connection_id",
                "mcp_authorization_attempt.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id"],
            ["tiktok_connection.tenant_id", "tiktok_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_connection_tool_observation_scope",
        "connection_tool_observation",
        ["tenant_id", "connection_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "mcp_refresh_attempt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("base_credential_revision", sa.Integer(), nullable=False),
        sa.Column("base_authorization_revision", sa.Integer(), nullable=False),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("claim_id", sa.Uuid(), nullable=True),
        sa.Column("claimed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_armed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "candidate_ciphertext", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "error_code", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','CLAIMED','REQUEST_ARMED','CANDIDATE_READY','PUBLISHED','OUTCOME_UNKNOWN','REJECTED','SUPERSEDED')",
            name="ck_mcp_refresh_attempt_status",
        ),
        sa.CheckConstraint(
            "(claim_id IS NULL) = (claimed_until IS NULL)",
            name="ck_mcp_refresh_attempt_claim",
        ),
        sa.CheckConstraint(
            "base_credential_revision >= 0 AND base_authorization_revision >= 0",
            name="ck_mcp_refresh_attempt_revisions",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id"],
            ["tiktok_connection.tenant_id", "tiktok_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mcp_refresh_attempt_tenant_id"),
        "mcp_refresh_attempt",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "uq_mcp_refresh_active_revision",
        "mcp_refresh_attempt",
        ["tenant_id", "connection_id", "base_credential_revision"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('PENDING','CLAIMED','REQUEST_ARMED','CANDIDATE_READY','OUTCOME_UNKNOWN')"
        ),
    )
    op.create_table(
        "bc_connection_binding",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id"],
            ["tenant_bc.tenant_id", "tenant_bc.bc_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id", "kind"],
            [
                "tiktok_connection.tenant_id",
                "tiktok_connection.id",
                "tiktok_connection.kind",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "bc_id", "connection_id"),
    )
    op.create_index(
        "uq_mcp_one_bc",
        "bc_connection_binding",
        ["tenant_id", "connection_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'OFFICIAL_MCP'"),
    )
    op.create_table(
        "bc_default_route",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "connection_id"],
            [
                "bc_connection_binding.tenant_id",
                "bc_connection_binding.bc_id",
                "bc_connection_binding.connection_id",
            ],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "bc_id"),
    )

    # 独立 MCP 候选外键同时约束租户与连接；一个 discovery 不能混用两类候选。
    op.add_column(
        "discovery_run", sa.Column("mcp_candidate_attempt_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        "fk_discovery_mcp_candidate",
        "discovery_run",
        "mcp_authorization_attempt",
        ["tenant_id", "connection_id", "mcp_candidate_attempt_id"],
        ["tenant_id", "connection_id", "id"],
    )
    op.create_check_constraint(
        "ck_discovery_candidate_exclusive",
        "discovery_run",
        "candidate_attempt_id IS NULL OR mcp_candidate_attempt_id IS NULL",
    )
    op.create_check_constraint(
        "ck_discovery_credential_revision", "discovery_run", "credential_revision >= 0"
    )
    # 既有 API 的多 BC 关系全部保留；只有唯一有效连接才自动建立默认。
    op.execute("""
        INSERT INTO bc_connection_binding (tenant_id, bc_id, connection_id, kind)
        SELECT DISTINCT tenant_id, bc_id, connection_id, 'OFFICIAL_API'
        FROM bc_account_access
    """)
    op.execute("""
        INSERT INTO bc_default_route (tenant_id, bc_id, connection_id)
        SELECT tenant_id, bc_id, (array_agg(connection_id))[1]
        FROM (
            SELECT DISTINCT a.tenant_id, a.bc_id, a.connection_id
            FROM bc_account_access a
            JOIN tiktok_connection c ON c.tenant_id = a.tenant_id AND c.id = a.connection_id
            JOIN tenant_bc bc ON bc.tenant_id = a.tenant_id AND bc.bc_id = a.bc_id
            WHERE c.status = 'ACTIVE' AND a.active AND a.in_bc AND a.authorized
                AND NOT bc.ownership_conflict
        ) eligible
        GROUP BY tenant_id, bc_id
        HAVING count(*) = 1
    """)
    for column in (
        "kind",
        "display_name",
        "authorization_revision",
        "adapter_contract_revision",
    ):
        op.alter_column("tiktok_connection", column, server_default=None)


def downgrade():
    # 旧 schema 无法区分 MCP 密文；先拒绝，避免降级后被当作 API 凭据使用。
    if (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT EXISTS (SELECT 1 FROM tiktok_connection WHERE kind = 'OFFICIAL_MCP')"
            )
        )
        .scalar_one()
    ):
        raise RuntimeError(
            "Cannot downgrade TikTok channels while MCP connections exist"
        )
    op.drop_constraint(
        "ck_discovery_credential_revision", "discovery_run", type_="check"
    )
    op.drop_constraint(
        "ck_discovery_candidate_exclusive", "discovery_run", type_="check"
    )
    op.drop_constraint(
        "fk_discovery_mcp_candidate", "discovery_run", type_="foreignkey"
    )
    op.drop_column("discovery_run", "mcp_candidate_attempt_id")
    for table in (
        "bc_default_route",
        "bc_connection_binding",
        "mcp_refresh_attempt",
        "connection_tool_observation",
        "connection_authorization",
        "mcp_authorization_attempt",
    ):
        op.drop_table(table)
    op.drop_constraint(
        "ck_tiktok_connection_authorization_revision",
        "tiktok_connection",
        type_="check",
    )
    op.drop_constraint("ck_tiktok_connection_kind", "tiktok_connection", type_="check")
    op.drop_constraint(
        "uq_tiktok_connection_tenant_kind", "tiktok_connection", type_="unique"
    )
    for column in (
        "adapter_contract_revision",
        "authorization_revision",
        "service_profile",
        "display_name",
        "kind",
    ):
        op.drop_column("tiktok_connection", column)
    for table, new, old in (
        ("build_scene_job", "credential_revision", "credential_version"),
        ("account_capability_job", "credential_revision", "credential_version"),
        ("discovery_run", "credential_revision", "credential_version"),
        (
            "authorization_attempt",
            "base_credential_revision",
            "base_credential_version",
        ),
        ("tiktok_connection", "credential_revision", "credential_version"),
    ):
        op.alter_column(
            table,
            new,
            new_column_name=old,
            existing_type=sa.Integer(),
            existing_nullable=False,
        )
