"""TikTok scene routes

Revision ID: mcp02
Revises: mcp_build_routes
Create Date: 2026-09-12 01:01:39.516986

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "mcp02"
down_revision = "mcp_build_routes"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "build_scene_job",
        sa.Column(
            "frozen_route", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_check_constraint(
        "ck_build_scene_job_frozen_route",
        "build_scene_job",
        "frozen_route IS NULL OR COALESCE((\njsonb_typeof(frozen_route) = 'object'\nAND frozen_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision']\nAND frozen_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] = '{}'::jsonb\nAND jsonb_typeof(frozen_route->'tenant_id') = 'string'\nAND jsonb_typeof(frozen_route->'bc_id') = 'string'\nAND jsonb_typeof(frozen_route->'connection_id') = 'string'\nAND jsonb_typeof(frozen_route->'channel') = 'string'\nAND jsonb_typeof(frozen_route->'authorization_revision') = 'number'\nAND jsonb_typeof(frozen_route->'adapter_contract_revision') = 'string'\nAND frozen_route->>'tenant_id' = tenant_id::text\nAND frozen_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'\nAND length(btrim(frozen_route->>'bc_id')) > 0\nAND frozen_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP')\nAND frozen_route->>'authorization_revision' ~ '^[0-9]+$'\nAND length(btrim(frozen_route->>'adapter_contract_revision')) > 0\n AND frozen_route->>'bc_id' = bc_id AND frozen_route->>'connection_id' = connection_id::text), false)",
    )
    op.add_column(
        "build_scene_job_page",
        sa.Column(
            "mcp_request_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
    )
    op.add_column(
        "build_scene_job_page",
        sa.Column(
            "remote_task_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
    )
    op.add_column(
        "draft_scene_preparation",
        sa.Column(
            "frozen_route", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_check_constraint(
        "ck_draft_scene_preparation_frozen_route",
        "draft_scene_preparation",
        "frozen_route IS NULL OR COALESCE((\njsonb_typeof(frozen_route) = 'object'\nAND frozen_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision']\nAND frozen_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] = '{}'::jsonb\nAND jsonb_typeof(frozen_route->'tenant_id') = 'string'\nAND jsonb_typeof(frozen_route->'bc_id') = 'string'\nAND jsonb_typeof(frozen_route->'connection_id') = 'string'\nAND jsonb_typeof(frozen_route->'channel') = 'string'\nAND jsonb_typeof(frozen_route->'authorization_revision') = 'number'\nAND jsonb_typeof(frozen_route->'adapter_contract_revision') = 'string'\nAND frozen_route->>'tenant_id' = tenant_id::text\nAND frozen_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'\nAND length(btrim(frozen_route->>'bc_id')) > 0\nAND frozen_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP')\nAND frozen_route->>'authorization_revision' ~ '^[0-9]+$'\nAND length(btrim(frozen_route->>'adapter_contract_revision')) > 0\n), false)",
    )
    # 旧场景未保存当时授权语义，保留事实并要求重新准备，不按今日默认补写。
    op.execute("""
        UPDATE build_scene_job SET status='STALE', error_code='scene_route_missing',
            claim_token=NULL, claimed_until=NULL
        WHERE frozen_route IS NULL AND status IN ('PENDING','COMPLETE');
        UPDATE draft_preparation p SET status='BLOCKED', error_code='scene_route_missing'
        WHERE p.status IN ('PENDING','READY') AND NOT EXISTS (
            SELECT 1 FROM draft_scene_preparation s
            WHERE s.tenant_id=p.tenant_id AND s.preparation_id=p.id AND s.frozen_route IS NOT NULL);
        UPDATE build_draft d SET status='BLOCKED'
        WHERE d.status IN ('PREPARING','READY') AND EXISTS (
            SELECT 1 FROM draft_preparation p WHERE p.tenant_id=d.tenant_id AND p.draft_id=d.id
                AND p.draft_revision=d.revision AND p.error_code='scene_route_missing');
        CREATE FUNCTION mcp_scene_route_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.frozen_route IS DISTINCT FROM OLD.frozen_route THEN
            RAISE EXCEPTION 'immutable scene route' USING ERRCODE='23514';
          END IF;
          RETURN NEW;
        END $$;
        CREATE TRIGGER build_scene_route_immutable BEFORE UPDATE ON build_scene_job
            FOR EACH ROW EXECUTE FUNCTION mcp_scene_route_immutable();
        CREATE TRIGGER draft_scene_route_immutable BEFORE UPDATE ON draft_scene_preparation
            FOR EACH ROW EXECUTE FUNCTION mcp_scene_route_immutable()
    """)


def downgrade():
    if (
        op.get_bind()
        .execute(
            sa.text("""
        SELECT EXISTS(SELECT 1 FROM build_scene_job WHERE frozen_route IS NOT NULL)
            OR EXISTS(SELECT 1 FROM draft_scene_preparation WHERE frozen_route IS NOT NULL)
            OR EXISTS(SELECT 1 FROM build_scene_job_page WHERE mcp_request_id IS NOT NULL OR remote_task_id IS NOT NULL)
    """)
        )
        .scalar_one()
    ):
        raise RuntimeError("frozen scene evidence cannot be downgraded")
    op.execute("""
        DROP TRIGGER build_scene_route_immutable ON build_scene_job;
        DROP TRIGGER draft_scene_route_immutable ON draft_scene_preparation;
        DROP FUNCTION mcp_scene_route_immutable()
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_draft_scene_preparation_frozen_route",
        "draft_scene_preparation",
        type_="check",
    )
    op.drop_column("draft_scene_preparation", "frozen_route")
    op.drop_column("build_scene_job_page", "remote_task_id")
    op.drop_column("build_scene_job_page", "mcp_request_id")
    op.drop_constraint(
        "ck_build_scene_job_frozen_route", "build_scene_job", type_="check"
    )
    op.drop_column("build_scene_job", "frozen_route")
    # ### end Alembic commands ###
