"""freeze material parent and operation routes

Revision ID: mcp_material_routes
Revises: mcp_directory_semantics
Create Date: 2026-09-12 01:44:08.312204

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "mcp_material_routes"
down_revision = "mcp_directory_semantics"
branch_labels = None
depends_on = None

ROUTES = {
    "ingest_session": ("frozen_route",),
    "material_asset_operation": ("frozen_route",),
    "material_cover_job": ("frozen_route",),
    "material_distribution": ("target_route", "source_route"),
    "upload_batch": ("frozen_route",),
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingest_session",
        sa.Column(
            "frozen_route",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.create_check_constraint(
        "ck_ingest_session_frozen_route",
        "ingest_session",
        "frozen_route IS NULL OR COALESCE((jsonb_typeof(frozen_route) = 'object' AND frozen_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND frozen_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] = '{}'::jsonb AND jsonb_typeof(frozen_route->'tenant_id') = 'string' AND jsonb_typeof(frozen_route->'bc_id') = 'string' AND jsonb_typeof(frozen_route->'connection_id') = 'string' AND jsonb_typeof(frozen_route->'channel') = 'string' AND jsonb_typeof(frozen_route->'authorization_revision') = 'number' AND jsonb_typeof(frozen_route->'adapter_contract_revision') = 'string' AND frozen_route->>'tenant_id' = tenant_id::text AND frozen_route->>'bc_id' = bc_id AND length(btrim(frozen_route->>'bc_id')) > 0 AND frozen_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND frozen_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP') AND frozen_route->>'authorization_revision' ~ '^[0-9]+$' AND length(btrim(frozen_route->>'adapter_contract_revision')) > 0), false)",
    )
    op.add_column(
        "material_asset_operation",
        sa.Column(
            "frozen_route",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.create_check_constraint(
        "ck_material_asset_operation_frozen_route",
        "material_asset_operation",
        "frozen_route IS NULL OR COALESCE((jsonb_typeof(frozen_route) = 'object' AND frozen_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND frozen_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] = '{}'::jsonb AND jsonb_typeof(frozen_route->'tenant_id') = 'string' AND jsonb_typeof(frozen_route->'bc_id') = 'string' AND jsonb_typeof(frozen_route->'connection_id') = 'string' AND jsonb_typeof(frozen_route->'channel') = 'string' AND jsonb_typeof(frozen_route->'authorization_revision') = 'number' AND jsonb_typeof(frozen_route->'adapter_contract_revision') = 'string' AND frozen_route->>'tenant_id' = tenant_id::text AND frozen_route->>'bc_id' = bc_id AND length(btrim(frozen_route->>'bc_id')) > 0 AND frozen_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND frozen_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP') AND frozen_route->>'authorization_revision' ~ '^[0-9]+$' AND length(btrim(frozen_route->>'adapter_contract_revision')) > 0), false)",
    )
    op.add_column(
        "material_cover_job",
        sa.Column(
            "frozen_route",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.create_check_constraint(
        "ck_material_cover_job_frozen_route",
        "material_cover_job",
        "frozen_route IS NULL OR COALESCE((jsonb_typeof(frozen_route) = 'object' AND frozen_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND frozen_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] = '{}'::jsonb AND jsonb_typeof(frozen_route->'tenant_id') = 'string' AND jsonb_typeof(frozen_route->'bc_id') = 'string' AND jsonb_typeof(frozen_route->'connection_id') = 'string' AND jsonb_typeof(frozen_route->'channel') = 'string' AND jsonb_typeof(frozen_route->'authorization_revision') = 'number' AND jsonb_typeof(frozen_route->'adapter_contract_revision') = 'string' AND frozen_route->>'tenant_id' = tenant_id::text AND frozen_route->>'bc_id' = bc_id AND length(btrim(frozen_route->>'bc_id')) > 0 AND frozen_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND frozen_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP') AND frozen_route->>'authorization_revision' ~ '^[0-9]+$' AND length(btrim(frozen_route->>'adapter_contract_revision')) > 0 AND frozen_route->>'connection_id' = connection_id::text), false)",
    )
    op.add_column(
        "material_distribution",
        sa.Column(
            "target_route",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "material_distribution",
        sa.Column(
            "source_route",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.create_check_constraint(
        "ck_material_distribution_source_route",
        "material_distribution",
        "source_route IS NULL OR COALESCE((jsonb_typeof(source_route) = 'object' AND source_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND source_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] = '{}'::jsonb AND jsonb_typeof(source_route->'tenant_id') = 'string' AND jsonb_typeof(source_route->'bc_id') = 'string' AND jsonb_typeof(source_route->'connection_id') = 'string' AND jsonb_typeof(source_route->'channel') = 'string' AND jsonb_typeof(source_route->'authorization_revision') = 'number' AND jsonb_typeof(source_route->'adapter_contract_revision') = 'string' AND source_route->>'tenant_id' = tenant_id::text AND source_route->>'bc_id' = bc_id AND length(btrim(source_route->>'bc_id')) > 0 AND source_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND source_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP') AND source_route->>'authorization_revision' ~ '^[0-9]+$' AND length(btrim(source_route->>'adapter_contract_revision')) > 0), false)",
    )
    op.create_check_constraint(
        "ck_material_distribution_target_route",
        "material_distribution",
        "target_route IS NULL OR COALESCE((jsonb_typeof(target_route) = 'object' AND target_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND target_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] = '{}'::jsonb AND jsonb_typeof(target_route->'tenant_id') = 'string' AND jsonb_typeof(target_route->'bc_id') = 'string' AND jsonb_typeof(target_route->'connection_id') = 'string' AND jsonb_typeof(target_route->'channel') = 'string' AND jsonb_typeof(target_route->'authorization_revision') = 'number' AND jsonb_typeof(target_route->'adapter_contract_revision') = 'string' AND target_route->>'tenant_id' = tenant_id::text AND target_route->>'bc_id' = bc_id AND length(btrim(target_route->>'bc_id')) > 0 AND target_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND target_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP') AND target_route->>'authorization_revision' ~ '^[0-9]+$' AND length(btrim(target_route->>'adapter_contract_revision')) > 0), false)",
    )
    op.add_column(
        "upload_batch",
        sa.Column(
            "frozen_route",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.create_check_constraint(
        "ck_upload_batch_frozen_route",
        "upload_batch",
        "frozen_route IS NULL OR COALESCE((jsonb_typeof(frozen_route) = 'object' AND frozen_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND frozen_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] = '{}'::jsonb AND jsonb_typeof(frozen_route->'tenant_id') = 'string' AND jsonb_typeof(frozen_route->'bc_id') = 'string' AND jsonb_typeof(frozen_route->'connection_id') = 'string' AND jsonb_typeof(frozen_route->'channel') = 'string' AND jsonb_typeof(frozen_route->'authorization_revision') = 'number' AND jsonb_typeof(frozen_route->'adapter_contract_revision') = 'string' AND frozen_route->>'tenant_id' = tenant_id::text AND frozen_route->>'bc_id' = bc_id AND length(btrim(frozen_route->>'bc_id')) > 0 AND frozen_route->>'connection_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' AND frozen_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP') AND frozen_route->>'authorization_revision' ~ '^[0-9]+$' AND length(btrim(frozen_route->>'adapter_contract_revision')) > 0), false)",
    )
    # 历史行维持 SQL NULL，不猜测当时授权；新记录还必须属于真实连接和 BC 绑定。
    op.execute("""
        CREATE FUNCTION mcp_material_route_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE field_name text; route_value jsonb;
        BEGIN
          FOREACH field_name IN ARRAY TG_ARGV LOOP
            route_value := to_jsonb(NEW)->field_name;
            IF TG_OP = 'UPDATE' THEN
              IF route_value IS DISTINCT FROM to_jsonb(OLD)->field_name THEN
                RAISE EXCEPTION 'immutable material route' USING ERRCODE='23514';
              END IF;
            ELSIF route_value IS DISTINCT FROM 'null'::jsonb THEN
              IF NOT EXISTS (
                SELECT 1 FROM public.tiktok_connection c
                JOIN public.bc_connection_binding b
                  ON b.tenant_id=c.tenant_id AND b.connection_id=c.id AND b.kind=c.kind
                WHERE c.tenant_id=NEW.tenant_id AND c.id::text=route_value->>'connection_id'
                  AND c.kind=route_value->>'channel' AND b.bc_id=NEW.bc_id
              ) THEN
                RAISE EXCEPTION 'material route connection scope mismatch' USING ERRCODE='23514';
              END IF;
            END IF;
          END LOOP;
          RETURN NEW;
        END $$
    """)
    for table, columns in ROUTES.items():
        arguments = ", ".join(f"'{column}'" for column in columns)
        op.execute(
            f"CREATE TRIGGER {table}_route_guard BEFORE INSERT OR UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION mcp_material_route_guard({arguments})"
        )


def downgrade():
    # 先锁住所有父表，避免检查之后、删列之前出现新的路由证据。
    op.execute("LOCK TABLE " + ", ".join(ROUTES) + " IN ACCESS EXCLUSIVE MODE")
    # 已保存的路由是未知操作核查所需证据，不能通过降级销毁。
    for table, columns in ROUTES.items():
        predicate = " OR ".join(f"{column} IS NOT NULL" for column in columns)
        if (
            op.get_bind()
            .execute(sa.text(f"SELECT EXISTS(SELECT 1 FROM {table} WHERE {predicate})"))
            .scalar_one()
        ):
            raise RuntimeError("frozen material evidence cannot be downgraded")
    for table in ROUTES:
        op.execute(f"DROP TRIGGER {table}_route_guard ON {table}")
    op.execute("DROP FUNCTION mcp_material_route_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_upload_batch_frozen_route", "upload_batch", type_="check")
    op.drop_column("upload_batch", "frozen_route")
    op.drop_constraint(
        "ck_material_distribution_target_route", "material_distribution", type_="check"
    )
    op.drop_constraint(
        "ck_material_distribution_source_route", "material_distribution", type_="check"
    )
    op.drop_column("material_distribution", "source_route")
    op.drop_column("material_distribution", "target_route")
    op.drop_constraint(
        "ck_material_cover_job_frozen_route", "material_cover_job", type_="check"
    )
    op.drop_column("material_cover_job", "frozen_route")
    op.drop_constraint(
        "ck_material_asset_operation_frozen_route",
        "material_asset_operation",
        type_="check",
    )
    op.drop_column("material_asset_operation", "frozen_route")
    op.drop_constraint(
        "ck_ingest_session_frozen_route", "ingest_session", type_="check"
    )
    op.drop_column("ingest_session", "frozen_route")
    # ### end Alembic commands ###
