"""audit reauthorized read-only build recovery

Revision ID: mcp_build_recovery
Revises: mcp_material_routes
Create Date: 2026-09-12 02:04:41.635591

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "mcp_build_recovery"
down_revision = "mcp_material_routes"
branch_labels = None
depends_on = None

IDENTITY_COLUMNS = (
    "id",
    "tenant_id",
    "request_id",
    "submission_id",
    "source_step_id",
    "source_attempt",
    "source_attempt_id",
    "connection_id",
    "bc_id",
    "advertiser_id",
    "old_authorization_revision",
    "new_authorization_revision",
    "request_actor_id",
    "source_request_digest",
    "old_route",
    "new_route",
    "authorization_proof",
    "created_at",
    "expires_at",
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build_historical_read",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("source_step_id", sa.Uuid(), nullable=False),
        sa.Column("source_attempt", sa.Integer(), nullable=False),
        sa.Column("source_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column(
            "advertiser_id",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.Column("old_authorization_revision", sa.Integer(), nullable=False),
        sa.Column("new_authorization_revision", sa.Integer(), nullable=False),
        sa.Column("request_actor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_request_digest",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("old_route", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("new_route", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "authorization_proof",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dispatch_revision", sa.Integer(), nullable=False),
        sa.Column("dispatch_id", sa.Uuid(), nullable=True),
        sa.Column("claim_token", sa.Uuid(), nullable=True),
        sa.Column("claimed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("repair_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "error_code", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True
        ),
        sa.Column(
            "remote_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("mismatch", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "coalesce((jsonb_typeof(old_route)='object' AND old_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND old_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] = '{}'::jsonb AND jsonb_typeof(old_route->'tenant_id')='string' AND jsonb_typeof(old_route->'bc_id')='string' AND jsonb_typeof(old_route->'connection_id')='string' AND jsonb_typeof(old_route->'channel')='string' AND jsonb_typeof(old_route->'adapter_contract_revision')='string' AND jsonb_typeof(old_route->'authorization_revision')='number' AND old_route->>'authorization_revision' ~ '^[0-9]+$' AND jsonb_typeof(new_route)='object' AND new_route ?& ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] AND new_route - ARRAY['tenant_id','bc_id','connection_id','channel','authorization_revision','adapter_contract_revision'] = '{}'::jsonb AND jsonb_typeof(new_route->'tenant_id')='string' AND jsonb_typeof(new_route->'bc_id')='string' AND jsonb_typeof(new_route->'connection_id')='string' AND jsonb_typeof(new_route->'channel')='string' AND jsonb_typeof(new_route->'adapter_contract_revision')='string' AND jsonb_typeof(new_route->'authorization_revision')='number' AND new_route->>'authorization_revision' ~ '^[0-9]+$'),false)",
            name="ck_historical_read_route_shape",
        ),
        sa.CheckConstraint(
            "coalesce(old_route->>'tenant_id'=tenant_id::text AND new_route->>'tenant_id'=tenant_id::text AND old_route->>'connection_id'=connection_id::text AND new_route->>'connection_id'=connection_id::text AND old_route->>'bc_id'=bc_id AND new_route->>'bc_id'=bc_id AND old_route->>'authorization_revision'=old_authorization_revision::text AND new_route->>'authorization_revision'=new_authorization_revision::text AND old_route->>'channel'=new_route->>'channel' AND old_route->>'channel' IN ('OFFICIAL_API','OFFICIAL_MCP') AND length(trim(old_route->>'adapter_contract_revision'))>0 AND length(trim(new_route->>'adapter_contract_revision'))>0,false)",
            name="ck_historical_read_route_scope",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(authorization_proof)='object' AND octet_length(authorization_proof::text)<=16384",
            name="ck_historical_read_proof",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(old_route)='object' AND jsonb_typeof(new_route)='object' AND octet_length(old_route::text)<=8192 AND octet_length(new_route::text)<=8192",
            name="ck_historical_read_routes",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(progress)='object' AND octet_length(progress::text)<=262144",
            name="ck_historical_read_progress",
        ),
        sa.CheckConstraint(
            "source_request_digest ~ '^[0-9a-f]{64}$'", name="ck_historical_read_digest"
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','CONFIRMED','UNKNOWN','BLOCKED')",
            name="ck_historical_read_status",
        ),
        sa.CheckConstraint(
            "(claim_token IS NULL)=(claimed_until IS NULL) AND dispatch_revision>=0",
            name="ck_historical_read_claim",
        ),
        sa.CheckConstraint(
            "old_authorization_revision>=0 AND new_authorization_revision>old_authorization_revision AND source_attempt>=0",
            name="ck_historical_read_revisions",
        ),
        sa.ForeignKeyConstraint(
            ["dispatch_id"],
            ["pending_dispatch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_actor_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "connection_id"],
            [
                "bc_connection_binding.tenant_id",
                "bc_connection_binding.bc_id",
                "bc_connection_binding.connection_id",
            ],
            name="fk_historical_read_binding",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id", "new_authorization_revision"],
            [
                "connection_authorization.tenant_id",
                "connection_authorization.connection_id",
                "connection_authorization.authorization_revision",
            ],
            name="fk_historical_read_new_authorization",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "connection_id", "old_authorization_revision"],
            [
                "connection_authorization.tenant_id",
                "connection_authorization.connection_id",
                "connection_authorization.authorization_revision",
            ],
            name="fk_historical_read_old_authorization",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_step_id", "source_attempt", "source_attempt_id"],
            [
                "build_attempt_context.tenant_id",
                "build_attempt_context.step_id",
                "build_attempt_context.attempt",
                "build_attempt_context.attempt_id",
            ],
            name="fk_historical_read_attempt",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "submission_id", "source_step_id"],
            [
                "execution_step.tenant_id",
                "execution_step.submission_id",
                "execution_step.id",
            ],
            name="fk_historical_read_source",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_historical_read_tenant"),
        sa.UniqueConstraint(
            "tenant_id", "request_id", name="uq_historical_read_request"
        ),
    )
    op.create_index(
        "ix_historical_read_repair",
        "build_historical_read",
        ["status", "repair_after", "id"],
        unique=False,
    )
    op.create_index(
        "ix_historical_read_source",
        "build_historical_read",
        ["tenant_id", "source_step_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "build_historical_read_page",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("read_id", sa.Uuid(), nullable=False),
        sa.Column("claim_token", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "call_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(call_evidence)='object' AND octet_length(call_evidence::text)<=16384",
            name="ck_historical_page_call",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(ids)='array' AND jsonb_array_length(ids)<=100",
            name="ck_historical_page_ids",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(summary)='object' AND octet_length(summary::text)<=262144",
            name="ck_historical_page_summary",
        ),
        sa.CheckConstraint(
            "stage IN ('OBJECT','STATUS') AND page BETWEEN 1 AND 1000",
            name="ck_historical_page_position",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "read_id"],
            ["build_historical_read.tenant_id", "build_historical_read.id"],
            name="fk_historical_page_read",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("read_id", "claim_token", name="uq_historical_page_claim"),
    )
    op.create_index(
        "ix_historical_page_scan",
        "build_historical_read_page",
        ["tenant_id", "read_id", "scan_id", "stage", "page"],
        unique=False,
    )
    old_identity = ",".join(f"OLD.{column}" for column in IDENTITY_COLUMNS)
    new_identity = ",".join(f"NEW.{column}" for column in IDENTITY_COLUMNS)
    # 原授权、明确核查请求与证明不可改写；只有有界任务进度可以推进。
    op.execute(f"""
        CREATE FUNCTION build_historical_read_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'historical read audit cannot be deleted' USING ERRCODE='23514';
          END IF;
          IF ROW({old_identity}) IS DISTINCT FROM ROW({new_identity}) THEN
            RAISE EXCEPTION 'historical read identity is immutable' USING ERRCODE='23514';
          END IF;
          RETURN NEW;
        END $$;
        CREATE TRIGGER build_historical_read_immutable BEFORE UPDATE OR DELETE
          ON build_historical_read FOR EACH ROW EXECUTE FUNCTION build_historical_read_guard();
        CREATE FUNCTION build_historical_page_guard() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'historical read pages are append only' USING ERRCODE='23514';
          RETURN NEW;
        END $$;
        CREATE TRIGGER build_historical_page_immutable BEFORE UPDATE OR DELETE
          ON build_historical_read_page FOR EACH ROW EXECUTE FUNCTION build_historical_page_guard()
    """)


def downgrade():
    # 写锁覆盖检查到 DDL 的整个事务，核查证据一旦存在就拒绝删除表。
    op.execute(
        "LOCK TABLE build_historical_read, build_historical_read_page IN ACCESS EXCLUSIVE MODE"
    )
    if (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT EXISTS(SELECT 1 FROM build_historical_read) OR EXISTS(SELECT 1 FROM build_historical_read_page)"
            )
        )
        .scalar_one()
    ):
        raise RuntimeError("historical build read evidence cannot be downgraded")
    op.execute("""
        DROP TRIGGER build_historical_page_immutable ON build_historical_read_page;
        DROP TRIGGER build_historical_read_immutable ON build_historical_read;
        DROP FUNCTION build_historical_page_guard();
        DROP FUNCTION build_historical_read_guard()
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_historical_page_scan", table_name="build_historical_read_page")
    op.drop_table("build_historical_read_page")
    op.drop_index("ix_historical_read_source", table_name="build_historical_read")
    op.drop_index("ix_historical_read_repair", table_name="build_historical_read")
    op.drop_table("build_historical_read")
    # ### end Alembic commands ###
