"""frozen build routes

Revision ID: mcp_build_routes
Revises: mcp_directory_bc_scope
Create Date: 2026-09-12 00:59:27.500727

"""

from uuid import NAMESPACE_URL, uuid5

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "mcp_build_routes"
down_revision = "mcp_directory_bc_scope"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build_route_context",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("preview_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bc_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("authorization_revision", sa.Integer(), nullable=False),
        sa.Column(
            "adapter_contract_revision",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('OFFICIAL_API','OFFICIAL_MCP')", name="ck_build_route_channel"
        ),
        sa.CheckConstraint(
            "authorization_revision >= 0 AND length(trim(adapter_contract_revision)) > 0",
            name="ck_build_route_revisions",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bc_id", "connection_id"],
            [
                "bc_connection_binding.tenant_id",
                "bc_connection_binding.bc_id",
                "bc_connection_binding.connection_id",
            ],
            name="fk_build_route_binding",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "preview_id", "bc_id"],
            ["build_preview.tenant_id", "build_preview.id", "build_preview.bc_id"],
            name="fk_build_route_preview",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "preview_id"),
    )
    op.create_table(
        "build_attempt_context",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("attempt >= 0", name="ck_build_attempt_count"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "submission_id", "step_id"],
            [
                "execution_step.tenant_id",
                "execution_step.submission_id",
                "execution_step.id",
            ],
            name="fk_build_attempt_step",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "step_id", "attempt"),
        sa.UniqueConstraint("attempt_id", name="uq_build_attempt_id"),
        sa.UniqueConstraint(
            "tenant_id",
            "step_id",
            "attempt",
            "attempt_id",
            name="uq_build_attempt_current_scope",
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "submission_id",
            "step_id",
            "attempt",
            name="uq_build_attempt_evidence_scope",
        ),
    )
    op.add_column("execution_step", sa.Column("attempt_id", sa.Uuid(), nullable=True))
    # 历史每次发送及回读追加证据仅旁挂稳定身份，绝不改计数和原始请求/回执。
    connection = op.get_bind()
    source = connection.execute(
        sa.text("""
        SELECT tenant_id, submission_id, id AS step_id, attempt FROM execution_step
        UNION
        SELECT tenant_id, submission_id, step_id, attempt FROM step_evidence
        ORDER BY tenant_id, step_id, attempt
    """)
    )
    while rows := source.fetchmany(1000):
        values = [dict(row._mapping) for row in rows]
        for value in values:
            value["attempt_id"] = uuid5(
                NAMESPACE_URL,
                f"tiktok-build-attempt:{value['tenant_id']}:{value['step_id']}:{value['attempt']}",
            )
        connection.execute(
            sa.text("""
            INSERT INTO build_attempt_context (tenant_id,submission_id,step_id,attempt,attempt_id)
            VALUES (:tenant_id,:submission_id,:step_id,:attempt,:attempt_id)
        """),
            values,
        )
    op.execute("""
        UPDATE execution_step s SET attempt_id=c.attempt_id
        FROM build_attempt_context c
        WHERE (s.tenant_id,s.id,s.attempt)=(c.tenant_id,c.step_id,c.attempt)
    """)
    # 旧版本没有保存当时的授权/契约修订，不能按今日默认或当前唯一连接补造。
    op.execute("""
        UPDATE build_submission SET error_code='legacy_route_unverifiable';
        UPDATE build_preview p SET status='OBSOLETE'
        WHERE p.status IN ('BUILDING','FROZEN')
          AND NOT EXISTS (SELECT 1 FROM build_submission s
              WHERE s.tenant_id=p.tenant_id AND s.preview_id=p.id)
    """)
    op.create_foreign_key(
        "fk_step_current_attempt",
        "execution_step",
        "build_attempt_context",
        ["tenant_id", "id", "attempt", "attempt_id"],
        ["tenant_id", "step_id", "attempt", "attempt_id"],
        initially="DEFERRED",
        deferrable=True,
        use_alter=True,
    )
    op.create_check_constraint(
        "ck_step_attempt_identity",
        "execution_step",
        "attempt = 0 OR attempt_id IS NOT NULL",
    )
    op.create_foreign_key(
        "fk_evidence_attempt_context",
        "step_evidence",
        "build_attempt_context",
        ["tenant_id", "submission_id", "step_id", "attempt"],
        ["tenant_id", "submission_id", "step_id", "attempt"],
        initially="DEFERRED",
        deferrable=True,
    )
    op.execute("""
        CREATE TRIGGER build_route_context_immutable BEFORE UPDATE OR DELETE ON build_route_context
        FOR EACH ROW EXECUTE FUNCTION build_execution_immutable();
        CREATE TRIGGER build_attempt_context_immutable BEFORE UPDATE OR DELETE ON build_attempt_context
        FOR EACH ROW EXECUTE FUNCTION build_execution_immutable();
        CREATE FUNCTION mcp_build_route_channel() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NOT EXISTS (SELECT 1 FROM bc_connection_binding b
              WHERE (b.tenant_id,b.bc_id,b.connection_id,b.kind)=
                    (NEW.tenant_id,NEW.bc_id,NEW.connection_id,NEW.channel)) THEN
            RAISE EXCEPTION 'frozen route channel mismatch' USING ERRCODE='23514';
          END IF;
          RETURN NEW;
        END $$;
        CREATE TRIGGER build_route_context_channel BEFORE INSERT ON build_route_context
        FOR EACH ROW EXECUTE FUNCTION mcp_build_route_channel()
    """)


def downgrade():
    # 已有冻结路由或历史attempt关联时必须保留，回滚靠兼容版本而非销毁证据。
    if (
        op.get_bind()
        .execute(
            sa.text("""
        SELECT EXISTS(SELECT 1 FROM build_route_context)
            OR EXISTS(SELECT 1 FROM build_attempt_context)
    """)
        )
        .scalar_one()
    ):
        raise RuntimeError("frozen build history cannot be downgraded")
    op.execute("DROP TRIGGER build_route_context_channel ON build_route_context")
    op.execute("DROP FUNCTION mcp_build_route_channel()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_evidence_attempt_context", "step_evidence", type_="foreignkey"
    )
    op.drop_constraint("ck_step_attempt_identity", "execution_step", type_="check")
    op.drop_constraint("fk_step_current_attempt", "execution_step", type_="foreignkey")
    op.drop_column("execution_step", "attempt_id")
    op.drop_table("build_attempt_context")
    op.drop_table("build_route_context")
    # ### end Alembic commands ###
