"""freeze capability authorization routes

Revision ID: mcp_capability_routes
Revises: mcp_stage_directory
Create Date: 2026-09-12 00:20:28.006083

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "mcp_capability_routes"
down_revision = "mcp_stage_directory"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account_capability_job",
        sa.Column(
            "channel", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True
        ),
    )
    op.add_column(
        "account_capability_job",
        sa.Column("authorization_revision", sa.Integer(), nullable=True),
    )
    op.add_column(
        "account_capability_job",
        sa.Column(
            "adapter_contract_revision",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
    )
    op.drop_index(
        op.f("uq_capability_active_basis"),
        table_name="account_capability_job",
        postgresql_where="((status)::text = 'PENDING'::text)",
    )
    op.create_index(
        "uq_capability_active_basis",
        "account_capability_job",
        [
            "tenant_id",
            "bc_id",
            "connection_id",
            "channel",
            "authorization_revision",
            "adapter_contract_revision",
            "directory_basis",
        ],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_check_constraint(
        "ck_capability_frozen_route",
        "account_capability_job",
        "(channel IS NULL AND authorization_revision IS NULL AND adapter_contract_revision IS NULL) OR (channel IS NOT NULL AND channel IN ('OFFICIAL_API','OFFICIAL_MCP') AND authorization_revision IS NOT NULL AND authorization_revision >= 0 AND adapter_contract_revision IS NOT NULL AND length(adapter_contract_revision) > 0)",
    )
    # 历史任务没有授权语义快照；保留原始 scope/role/计数，只停止复用。
    # 不以今天的连接版本或默认 BC 路由补写过去的权限事实。
    op.execute(
        sa.text("""
        UPDATE account_capability_job
        SET status = 'STALE', phase = 'DONE',
            error_code = 'capability_evidence_stale',
            claim_token = NULL, claimed_until = NULL
        WHERE status IN ('PENDING', 'COMPLETE')
    """)
    )


def downgrade():
    # 新权限任务已经依赖冻结语义时禁止降级，否则旧代码会重用错误凭据版本。
    if (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT EXISTS (SELECT 1 FROM account_capability_job WHERE channel IS NOT NULL)"
            )
        )
        .scalar_one()
    ):
        raise RuntimeError("cannot discard frozen capability routes")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_capability_frozen_route", "account_capability_job", type_="check"
    )
    op.drop_index(
        "uq_capability_active_basis",
        table_name="account_capability_job",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_index(
        op.f("uq_capability_active_basis"),
        "account_capability_job",
        [
            "tenant_id",
            "bc_id",
            "connection_id",
            "credential_revision",
            "directory_basis",
        ],
        unique=True,
        postgresql_where="((status)::text = 'PENDING'::text)",
    )
    op.drop_column("account_capability_job", "adapter_contract_revision")
    op.drop_column("account_capability_job", "authorization_revision")
    op.drop_column("account_capability_job", "channel")
    # ### end Alembic commands ###
