"""scoped report query snapshots

Revision ID: reporting_queries
Revises: ads_reporting_data
Create Date: 2026-09-30 22:20:11.170815

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'reporting_queries'
down_revision = 'ads_reporting_data'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frozen_selection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('bc_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('advertiser_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filter_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('publication_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('naming_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('material_uses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('membership_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='ck_frozen_selection_expiry'),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'bc_id'], ['tenant_bc.tenant_id', 'tenant_bc.bc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_frozen_selection_owner_expiry', 'frozen_selection', ['tenant_id', 'bc_id', 'actor_id', 'expires_at'], unique=False)
    op.create_table('query_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('bc_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('advertiser_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filter_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('publication_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('naming_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trends', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='ck_query_snapshot_expiry'),
    sa.CheckConstraint('total >= 0', name='ck_query_snapshot_total'),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'bc_id'], ['tenant_bc.tenant_id', 'tenant_bc.bc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_snapshot_expiry', 'query_snapshot', ['expires_at'], unique=False)
    op.create_index('ix_query_snapshot_owner_expiry', 'query_snapshot', ['tenant_id', 'bc_id', 'actor_id', 'expires_at'], unique=False)
    op.create_table('report_export',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('bc_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('advertiser_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filter_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('publication_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('naming_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('frozen_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED','RUNNING','COMPLETE','FAILED','EXPIRED')", name='ck_report_export_status'),
    sa.CheckConstraint('expires_at > created_at', name='ck_report_export_expiry'),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'bc_id'], ['tenant_bc.tenant_id', 'tenant_bc.bc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_export_expiry', 'report_export', ['expires_at'], unique=False)
    op.create_index('ix_report_export_idempotency', 'report_export', ['tenant_id', 'bc_id', 'actor_id', 'idempotency_key'], unique=True)
    op.create_index('ix_report_export_owner_status', 'report_export', ['tenant_id', 'bc_id', 'actor_id', 'status'], unique=False)
    op.create_table('saved_report_view',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('bc_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'bc_id'], ['tenant_bc.tenant_id', 'tenant_bc.bc_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_report_view_owner', 'saved_report_view', ['tenant_id', 'bc_id', 'actor_id', 'name'], unique=False)
    op.create_table('query_snapshot_row',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('row_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('stable_sequence', sa.Integer(), nullable=False),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('display', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('material_uses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metric_buckets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('directory_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('membership_digest', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.CheckConstraint("dimension IN ('account','campaign','adgroup','ad','material','drama')", name='ck_query_snapshot_row_dimension'),
    sa.CheckConstraint('stable_sequence >= 0', name='ck_query_snapshot_row_sequence'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['query_snapshot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'row_key')
    )
    op.create_index('ix_query_snapshot_row_sequence', 'query_snapshot_row', ['snapshot_id', 'stable_sequence'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_query_snapshot_row_sequence', table_name='query_snapshot_row')
    op.drop_table('query_snapshot_row')
    op.drop_index('ix_saved_report_view_owner', table_name='saved_report_view')
    op.drop_table('saved_report_view')
    op.drop_index('ix_report_export_owner_status', table_name='report_export')
    op.drop_index('ix_report_export_idempotency', table_name='report_export')
    op.drop_index('ix_report_export_expiry', table_name='report_export')
    op.drop_table('report_export')
    op.drop_index('ix_query_snapshot_owner_expiry', table_name='query_snapshot')
    op.drop_index('ix_query_snapshot_expiry', table_name='query_snapshot')
    op.drop_table('query_snapshot')
    op.drop_index('ix_frozen_selection_owner_expiry', table_name='frozen_selection')
    op.drop_table('frozen_selection')
    # ### end Alembic commands ###
