/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAccountsRouteImport } from './routes/_layout/accounts'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutBuildTasksRouteImport } from './routes/_layout/build-tasks'
import { Route as LayoutMaterialsRouteImport } from './routes/_layout/materials'
import { Route as LayoutMembersRouteImport } from './routes/_layout/members'
import { Route as LayoutProvidersRouteImport } from './routes/_layout/providers'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutStrategiesRouteImport } from './routes/_layout/strategies'
import { Route as LayoutPlatformTenantsRouteImport } from './routes/_layout/platform.tenants'
import { Route as LayoutTenantsTenantIdRouteImport } from './routes/_layout/tenants.$tenantId'
import { Route as LayoutTenantsTenantIdIndexRouteImport } from './routes/_layout/tenants.$tenantId.index'
import { Route as LayoutTenantsTenantIdAccountsRouteImport } from './routes/_layout/tenants.$tenantId.accounts'
import { Route as LayoutTenantsTenantIdBuildTasksRouteImport } from './routes/_layout/tenants.$tenantId.build-tasks'
import { Route as LayoutTenantsTenantIdMaterialsRouteImport } from './routes/_layout/tenants.$tenantId.materials'
import { Route as LayoutTenantsTenantIdMembersRouteImport } from './routes/_layout/tenants.$tenantId.members'
import { Route as LayoutTenantsTenantIdProvidersRouteImport } from './routes/_layout/tenants.$tenantId.providers'
import { Route as LayoutTenantsTenantIdStrategiesRouteImport } from './routes/_layout/tenants.$tenantId.strategies'
import { Route as LayoutTenantsTenantIdBuildsNewRouteImport } from './routes/_layout/tenants.$tenantId.builds.new'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountsRoute = LayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuildTasksRoute = LayoutBuildTasksRouteImport.update({
  id: '/build-tasks',
  path: '/build-tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMaterialsRoute = LayoutMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMembersRoute = LayoutMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProvidersRoute = LayoutProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStrategiesRoute = LayoutStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlatformTenantsRoute = LayoutPlatformTenantsRouteImport.update({
  id: '/platform/tenants',
  path: '/platform/tenants',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTenantsTenantIdRoute = LayoutTenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTenantsTenantIdIndexRoute =
  LayoutTenantsTenantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutTenantsTenantIdRoute,
  } as any)
const LayoutTenantsTenantIdAccountsRoute =
  LayoutTenantsTenantIdAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => LayoutTenantsTenantIdRoute,
  } as any)
const LayoutTenantsTenantIdBuildTasksRoute =
  LayoutTenantsTenantIdBuildTasksRouteImport.update({
    id: '/build-tasks',
    path: '/build-tasks',
    getParentRoute: () => LayoutTenantsTenantIdRoute,
  } as any)
const LayoutTenantsTenantIdMaterialsRoute =
  LayoutTenantsTenantIdMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => LayoutTenantsTenantIdRoute,
  } as any)
const LayoutTenantsTenantIdMembersRoute =
  LayoutTenantsTenantIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LayoutTenantsTenantIdRoute,
  } as any)
const LayoutTenantsTenantIdProvidersRoute =
  LayoutTenantsTenantIdProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => LayoutTenantsTenantIdRoute,
  } as any)
const LayoutTenantsTenantIdStrategiesRoute =
  LayoutTenantsTenantIdStrategiesRouteImport.update({
    id: '/strategies',
    path: '/strategies',
    getParentRoute: () => LayoutTenantsTenantIdRoute,
  } as any)
const LayoutTenantsTenantIdBuildsNewRoute =
  LayoutTenantsTenantIdBuildsNewRouteImport.update({
    id: '/builds/new',
    path: '/builds/new',
    getParentRoute: () => LayoutTenantsTenantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof LayoutAccountsRoute
  '/admin': typeof LayoutAdminRoute
  '/build-tasks': typeof LayoutBuildTasksRoute
  '/materials': typeof LayoutMaterialsRoute
  '/members': typeof LayoutMembersRoute
  '/providers': typeof LayoutProvidersRoute
  '/settings': typeof LayoutSettingsRoute
  '/strategies': typeof LayoutStrategiesRoute
  '/platform/tenants': typeof LayoutPlatformTenantsRoute
  '/tenants/$tenantId': typeof LayoutTenantsTenantIdRouteWithChildren
  '/tenants/$tenantId/accounts': typeof LayoutTenantsTenantIdAccountsRoute
  '/tenants/$tenantId/build-tasks': typeof LayoutTenantsTenantIdBuildTasksRoute
  '/tenants/$tenantId/materials': typeof LayoutTenantsTenantIdMaterialsRoute
  '/tenants/$tenantId/members': typeof LayoutTenantsTenantIdMembersRoute
  '/tenants/$tenantId/providers': typeof LayoutTenantsTenantIdProvidersRoute
  '/tenants/$tenantId/strategies': typeof LayoutTenantsTenantIdStrategiesRoute
  '/tenants/$tenantId/': typeof LayoutTenantsTenantIdIndexRoute
  '/tenants/$tenantId/builds/new': typeof LayoutTenantsTenantIdBuildsNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof LayoutAccountsRoute
  '/admin': typeof LayoutAdminRoute
  '/build-tasks': typeof LayoutBuildTasksRoute
  '/materials': typeof LayoutMaterialsRoute
  '/members': typeof LayoutMembersRoute
  '/providers': typeof LayoutProvidersRoute
  '/settings': typeof LayoutSettingsRoute
  '/strategies': typeof LayoutStrategiesRoute
  '/': typeof LayoutIndexRoute
  '/platform/tenants': typeof LayoutPlatformTenantsRoute
  '/tenants/$tenantId/accounts': typeof LayoutTenantsTenantIdAccountsRoute
  '/tenants/$tenantId/build-tasks': typeof LayoutTenantsTenantIdBuildTasksRoute
  '/tenants/$tenantId/materials': typeof LayoutTenantsTenantIdMaterialsRoute
  '/tenants/$tenantId/members': typeof LayoutTenantsTenantIdMembersRoute
  '/tenants/$tenantId/providers': typeof LayoutTenantsTenantIdProvidersRoute
  '/tenants/$tenantId/strategies': typeof LayoutTenantsTenantIdStrategiesRoute
  '/tenants/$tenantId': typeof LayoutTenantsTenantIdIndexRoute
  '/tenants/$tenantId/builds/new': typeof LayoutTenantsTenantIdBuildsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/accounts': typeof LayoutAccountsRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/build-tasks': typeof LayoutBuildTasksRoute
  '/_layout/materials': typeof LayoutMaterialsRoute
  '/_layout/members': typeof LayoutMembersRoute
  '/_layout/providers': typeof LayoutProvidersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/strategies': typeof LayoutStrategiesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/platform/tenants': typeof LayoutPlatformTenantsRoute
  '/_layout/tenants/$tenantId': typeof LayoutTenantsTenantIdRouteWithChildren
  '/_layout/tenants/$tenantId/accounts': typeof LayoutTenantsTenantIdAccountsRoute
  '/_layout/tenants/$tenantId/build-tasks': typeof LayoutTenantsTenantIdBuildTasksRoute
  '/_layout/tenants/$tenantId/materials': typeof LayoutTenantsTenantIdMaterialsRoute
  '/_layout/tenants/$tenantId/members': typeof LayoutTenantsTenantIdMembersRoute
  '/_layout/tenants/$tenantId/providers': typeof LayoutTenantsTenantIdProvidersRoute
  '/_layout/tenants/$tenantId/strategies': typeof LayoutTenantsTenantIdStrategiesRoute
  '/_layout/tenants/$tenantId/': typeof LayoutTenantsTenantIdIndexRoute
  '/_layout/tenants/$tenantId/builds/new': typeof LayoutTenantsTenantIdBuildsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/accounts'
    | '/admin'
    | '/build-tasks'
    | '/materials'
    | '/members'
    | '/providers'
    | '/settings'
    | '/strategies'
    | '/platform/tenants'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/accounts'
    | '/tenants/$tenantId/build-tasks'
    | '/tenants/$tenantId/materials'
    | '/tenants/$tenantId/members'
    | '/tenants/$tenantId/providers'
    | '/tenants/$tenantId/strategies'
    | '/tenants/$tenantId/'
    | '/tenants/$tenantId/builds/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/accounts'
    | '/admin'
    | '/build-tasks'
    | '/materials'
    | '/members'
    | '/providers'
    | '/settings'
    | '/strategies'
    | '/'
    | '/platform/tenants'
    | '/tenants/$tenantId/accounts'
    | '/tenants/$tenantId/build-tasks'
    | '/tenants/$tenantId/materials'
    | '/tenants/$tenantId/members'
    | '/tenants/$tenantId/providers'
    | '/tenants/$tenantId/strategies'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/builds/new'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/accounts'
    | '/_layout/admin'
    | '/_layout/build-tasks'
    | '/_layout/materials'
    | '/_layout/members'
    | '/_layout/providers'
    | '/_layout/settings'
    | '/_layout/strategies'
    | '/_layout/'
    | '/_layout/platform/tenants'
    | '/_layout/tenants/$tenantId'
    | '/_layout/tenants/$tenantId/accounts'
    | '/_layout/tenants/$tenantId/build-tasks'
    | '/_layout/tenants/$tenantId/materials'
    | '/_layout/tenants/$tenantId/members'
    | '/_layout/tenants/$tenantId/providers'
    | '/_layout/tenants/$tenantId/strategies'
    | '/_layout/tenants/$tenantId/'
    | '/_layout/tenants/$tenantId/builds/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accounts': {
      id: '/_layout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof LayoutAccountsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/build-tasks': {
      id: '/_layout/build-tasks'
      path: '/build-tasks'
      fullPath: '/build-tasks'
      preLoaderRoute: typeof LayoutBuildTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/materials': {
      id: '/_layout/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof LayoutMaterialsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/members': {
      id: '/_layout/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof LayoutMembersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/providers': {
      id: '/_layout/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof LayoutProvidersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/strategies': {
      id: '/_layout/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof LayoutStrategiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/platform/tenants': {
      id: '/_layout/platform/tenants'
      path: '/platform/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof LayoutPlatformTenantsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tenants/$tenantId': {
      id: '/_layout/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof LayoutTenantsTenantIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tenants/$tenantId/': {
      id: '/_layout/tenants/$tenantId/'
      path: '/'
      fullPath: '/tenants/$tenantId/'
      preLoaderRoute: typeof LayoutTenantsTenantIdIndexRouteImport
      parentRoute: typeof LayoutTenantsTenantIdRoute
    }
    '/_layout/tenants/$tenantId/accounts': {
      id: '/_layout/tenants/$tenantId/accounts'
      path: '/accounts'
      fullPath: '/tenants/$tenantId/accounts'
      preLoaderRoute: typeof LayoutTenantsTenantIdAccountsRouteImport
      parentRoute: typeof LayoutTenantsTenantIdRoute
    }
    '/_layout/tenants/$tenantId/build-tasks': {
      id: '/_layout/tenants/$tenantId/build-tasks'
      path: '/build-tasks'
      fullPath: '/tenants/$tenantId/build-tasks'
      preLoaderRoute: typeof LayoutTenantsTenantIdBuildTasksRouteImport
      parentRoute: typeof LayoutTenantsTenantIdRoute
    }
    '/_layout/tenants/$tenantId/materials': {
      id: '/_layout/tenants/$tenantId/materials'
      path: '/materials'
      fullPath: '/tenants/$tenantId/materials'
      preLoaderRoute: typeof LayoutTenantsTenantIdMaterialsRouteImport
      parentRoute: typeof LayoutTenantsTenantIdRoute
    }
    '/_layout/tenants/$tenantId/members': {
      id: '/_layout/tenants/$tenantId/members'
      path: '/members'
      fullPath: '/tenants/$tenantId/members'
      preLoaderRoute: typeof LayoutTenantsTenantIdMembersRouteImport
      parentRoute: typeof LayoutTenantsTenantIdRoute
    }
    '/_layout/tenants/$tenantId/providers': {
      id: '/_layout/tenants/$tenantId/providers'
      path: '/providers'
      fullPath: '/tenants/$tenantId/providers'
      preLoaderRoute: typeof LayoutTenantsTenantIdProvidersRouteImport
      parentRoute: typeof LayoutTenantsTenantIdRoute
    }
    '/_layout/tenants/$tenantId/strategies': {
      id: '/_layout/tenants/$tenantId/strategies'
      path: '/strategies'
      fullPath: '/tenants/$tenantId/strategies'
      preLoaderRoute: typeof LayoutTenantsTenantIdStrategiesRouteImport
      parentRoute: typeof LayoutTenantsTenantIdRoute
    }
    '/_layout/tenants/$tenantId/builds/new': {
      id: '/_layout/tenants/$tenantId/builds/new'
      path: '/builds/new'
      fullPath: '/tenants/$tenantId/builds/new'
      preLoaderRoute: typeof LayoutTenantsTenantIdBuildsNewRouteImport
      parentRoute: typeof LayoutTenantsTenantIdRoute
    }
  }
}

interface LayoutTenantsTenantIdRouteChildren {
  LayoutTenantsTenantIdAccountsRoute: typeof LayoutTenantsTenantIdAccountsRoute
  LayoutTenantsTenantIdBuildTasksRoute: typeof LayoutTenantsTenantIdBuildTasksRoute
  LayoutTenantsTenantIdMaterialsRoute: typeof LayoutTenantsTenantIdMaterialsRoute
  LayoutTenantsTenantIdMembersRoute: typeof LayoutTenantsTenantIdMembersRoute
  LayoutTenantsTenantIdProvidersRoute: typeof LayoutTenantsTenantIdProvidersRoute
  LayoutTenantsTenantIdStrategiesRoute: typeof LayoutTenantsTenantIdStrategiesRoute
  LayoutTenantsTenantIdIndexRoute: typeof LayoutTenantsTenantIdIndexRoute
  LayoutTenantsTenantIdBuildsNewRoute: typeof LayoutTenantsTenantIdBuildsNewRoute
}

const LayoutTenantsTenantIdRouteChildren: LayoutTenantsTenantIdRouteChildren = {
  LayoutTenantsTenantIdAccountsRoute: LayoutTenantsTenantIdAccountsRoute,
  LayoutTenantsTenantIdBuildTasksRoute: LayoutTenantsTenantIdBuildTasksRoute,
  LayoutTenantsTenantIdMaterialsRoute: LayoutTenantsTenantIdMaterialsRoute,
  LayoutTenantsTenantIdMembersRoute: LayoutTenantsTenantIdMembersRoute,
  LayoutTenantsTenantIdProvidersRoute: LayoutTenantsTenantIdProvidersRoute,
  LayoutTenantsTenantIdStrategiesRoute: LayoutTenantsTenantIdStrategiesRoute,
  LayoutTenantsTenantIdIndexRoute: LayoutTenantsTenantIdIndexRoute,
  LayoutTenantsTenantIdBuildsNewRoute: LayoutTenantsTenantIdBuildsNewRoute,
}

const LayoutTenantsTenantIdRouteWithChildren =
  LayoutTenantsTenantIdRoute._addFileChildren(
    LayoutTenantsTenantIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAccountsRoute: typeof LayoutAccountsRoute
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBuildTasksRoute: typeof LayoutBuildTasksRoute
  LayoutMaterialsRoute: typeof LayoutMaterialsRoute
  LayoutMembersRoute: typeof LayoutMembersRoute
  LayoutProvidersRoute: typeof LayoutProvidersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStrategiesRoute: typeof LayoutStrategiesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPlatformTenantsRoute: typeof LayoutPlatformTenantsRoute
  LayoutTenantsTenantIdRoute: typeof LayoutTenantsTenantIdRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountsRoute: LayoutAccountsRoute,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBuildTasksRoute: LayoutBuildTasksRoute,
  LayoutMaterialsRoute: LayoutMaterialsRoute,
  LayoutMembersRoute: LayoutMembersRoute,
  LayoutProvidersRoute: LayoutProvidersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStrategiesRoute: LayoutStrategiesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPlatformTenantsRoute: LayoutPlatformTenantsRoute,
  LayoutTenantsTenantIdRoute: LayoutTenantsTenantIdRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
