/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAccountsRouteImport } from './routes/_layout/accounts'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutBuildTasksRouteImport } from './routes/_layout/build-tasks'
import { Route as LayoutMaterialsRouteImport } from './routes/_layout/materials'
import { Route as LayoutMembersRouteImport } from './routes/_layout/members'
import { Route as LayoutProvidersRouteImport } from './routes/_layout/providers'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutStrategiesRouteImport } from './routes/_layout/strategies'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountsRoute = LayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBuildTasksRoute = LayoutBuildTasksRouteImport.update({
  id: '/build-tasks',
  path: '/build-tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMaterialsRoute = LayoutMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMembersRoute = LayoutMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProvidersRoute = LayoutProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStrategiesRoute = LayoutStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof LayoutAccountsRoute
  '/admin': typeof LayoutAdminRoute
  '/build-tasks': typeof LayoutBuildTasksRoute
  '/materials': typeof LayoutMaterialsRoute
  '/members': typeof LayoutMembersRoute
  '/providers': typeof LayoutProvidersRoute
  '/settings': typeof LayoutSettingsRoute
  '/strategies': typeof LayoutStrategiesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof LayoutAccountsRoute
  '/admin': typeof LayoutAdminRoute
  '/build-tasks': typeof LayoutBuildTasksRoute
  '/materials': typeof LayoutMaterialsRoute
  '/members': typeof LayoutMembersRoute
  '/providers': typeof LayoutProvidersRoute
  '/settings': typeof LayoutSettingsRoute
  '/strategies': typeof LayoutStrategiesRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/accounts': typeof LayoutAccountsRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/build-tasks': typeof LayoutBuildTasksRoute
  '/_layout/materials': typeof LayoutMaterialsRoute
  '/_layout/members': typeof LayoutMembersRoute
  '/_layout/providers': typeof LayoutProvidersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/strategies': typeof LayoutStrategiesRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/accounts'
    | '/admin'
    | '/build-tasks'
    | '/materials'
    | '/members'
    | '/providers'
    | '/settings'
    | '/strategies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/accounts'
    | '/admin'
    | '/build-tasks'
    | '/materials'
    | '/members'
    | '/providers'
    | '/settings'
    | '/strategies'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/accounts'
    | '/_layout/admin'
    | '/_layout/build-tasks'
    | '/_layout/materials'
    | '/_layout/members'
    | '/_layout/providers'
    | '/_layout/settings'
    | '/_layout/strategies'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accounts': {
      id: '/_layout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof LayoutAccountsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/build-tasks': {
      id: '/_layout/build-tasks'
      path: '/build-tasks'
      fullPath: '/build-tasks'
      preLoaderRoute: typeof LayoutBuildTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/materials': {
      id: '/_layout/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof LayoutMaterialsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/members': {
      id: '/_layout/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof LayoutMembersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/providers': {
      id: '/_layout/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof LayoutProvidersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/strategies': {
      id: '/_layout/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof LayoutStrategiesRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAccountsRoute: typeof LayoutAccountsRoute
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBuildTasksRoute: typeof LayoutBuildTasksRoute
  LayoutMaterialsRoute: typeof LayoutMaterialsRoute
  LayoutMembersRoute: typeof LayoutMembersRoute
  LayoutProvidersRoute: typeof LayoutProvidersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStrategiesRoute: typeof LayoutStrategiesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountsRoute: LayoutAccountsRoute,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBuildTasksRoute: LayoutBuildTasksRoute,
  LayoutMaterialsRoute: LayoutMaterialsRoute,
  LayoutMembersRoute: LayoutMembersRoute,
  LayoutProvidersRoute: LayoutProvidersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStrategiesRoute: LayoutStrategiesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
